package com.skyerzz.hypixellib.util.achievements;

/**
 * Created by sky on 11-11-2017.
 */
public enum SingleAchievement {
    //<editor-fold desc="[Single Achievements]">
    WARLORDS_MEDIUM_RARE(AchievementGameType.WARLORDS, 10, "Medium Rare", "Receive a Rare weapon from The Weaponsmith."),
    WARLORDS_COMING_THROUGH(AchievementGameType.WARLORDS, 5, "Coming Through!", "Get a kill while under the Berserk Ultimate."),
    WARLORDS_WARLORD(AchievementGameType.WARLORDS, 10, "Warlord", "Obtain Lv90 with any class."),
    WARLORDS_GREEN_IS_LOVE(AchievementGameType.WARLORDS, 10, "Green Is Love, Green Is Life", "Pick up the healing powerup while having less than 100 health remaining."),
    WARLORDS_MAD_SKILLZ_YO(AchievementGameType.WARLORDS, 10, "Mad Skills, Yo!", "Unlock all the Skill Upgrades for a class."),
    WARLORDS_HAMMER_OF_DESTRUCTION(AchievementGameType.WARLORDS, 5, "Hammer of Destruction", "Hit 10 targets with only 1 Hammer of Light."),
    WARLORDS_EXTENSIVE_TRAINING(AchievementGameType.WARLORDS, 10, "Extensive Training", "Unlock all the Combat Upgrades for a class."),
    WARLORDS_EAGLE_EYED(AchievementGameType.WARLORDS, 10, "Eagle Eyed", "Kill a player in TDM within 30 seconds of respawning."),
    WARLORDS_THAT_WAS_EASY(AchievementGameType.WARLORDS, 5, "That Was Easy", "Win by 500 points in Team Deathmatch."),
    WARLORDS_CAPTURE_THE_WIN(AchievementGameType.WARLORDS, 5, "Capture The Win!", "Capture 3 flags in one game of CTF."),
    WARLORDS_I_HAVE_TO_CONCENTRATE(AchievementGameType.WARLORDS, 5, "I Have to Concentrate", "Get a kill with Consecrate."),
    WARLORDS_JUICED_UP(AchievementGameType.WARLORDS, 10, "Juiced Up!", "Get a killing blow on an enemy player while under the effect of the damage powerup."),
    WARLORDS_ARE_YOU_KIDDING_ME(AchievementGameType.WARLORDS, 10, "Are You Kidding Me!?", "Salvage a Legendary weapon."),
    WARLORDS_SHARDS_FOR_GLORY(AchievementGameType.WARLORDS, 15, "Shards for Glory", "Fully max a crafted Legendary weapon."),
    WARLORDS_TOTAL_DOMINATION(AchievementGameType.WARLORDS, 5, "Total Domination", "Capture all domination points at once."),
    WARLORDS_NIFTY(AchievementGameType.WARLORDS, 10, "Nifty", "Survive a game of Team Deathmatch with at least one kill, without dying yourself."),
    WARLORDS_MAKIN_SOME_ROOM(AchievementGameType.WARLORDS, 10, "Makin' Some Room", "Salvage a Weapon."),
    WARLORDS_LIFELEECH(AchievementGameType.WARLORDS, 5, "Lifeleech", "Heal yourself for a total of at least 1000 health with the Earthliving weapon."),
    WARLORDS_SLOW_DOWN_THERE(AchievementGameType.WARLORDS, 5, "Slow Down There", "Kill someone with a Freezing Breath while holding a flag."),
    WARLORDS_GIDDY_UP(AchievementGameType.WARLORDS, 10, "Giddy Up!", "Unlock a mount variation."),
    WARLORDS_BEEP_BEEP(AchievementGameType.WARLORDS, 10, "Beep Beep!", "Capture a flag while under the effect of the speed powerup."),
    WARLORDS_AVENGERS_WRATH(AchievementGameType.WARLORDS, 5, "Avenger's Wrath", "Get a double strike kill when under the effect of Avenger's Wrath."),
    WARLORDS_THIS_BETTER_BE_GOOD(AchievementGameType.WARLORDS, 10, "This Better Be Good!", "Perform a Stats Reroll on a Legendary weapon."),
    WARLORDS_I_GOT_YOU_BRO(AchievementGameType.WARLORDS, 5, "I Got You Bro", "Use Intervene on a player who is below 500 HP."),
    WARLORDS_I_MUST_RESIST(AchievementGameType.WARLORDS, 10, "I...Must...Resist", "Completely fill up your Broken Weapons inventory."),
    WARLORDS_COLLATERAL_DAMAGE(AchievementGameType.WARLORDS, 5, "Collateral Damage", "Kill 2 players with one Chain Lightning."),
    WARLORDS_FEELING_SPECIAL(AchievementGameType.WARLORDS, 10, "Feeling Special!", "Change your weapon's appearance using the Skin Selector."),
    WARLORDS_FIRST_OF_MANY(AchievementGameType.WARLORDS, 10, "The First Of Many", "Get a Broken Weapon repaired by The Weaponsmith."),
    WARLORDS_PURPLE_POWER(AchievementGameType.WARLORDS, 10, "Purple Power!", "Receive an Epic weapon from The Weaponsmith."),
    WARLORDS_LEGENDARY(AchievementGameType.WARLORDS, 10, "Legen...Wait For It...Dary!", "Receive a Legendary weapon from The Weaponsmith."),
    WARLORDS_CHAIN_KILL(AchievementGameType.WARLORDS, 10, "Chain Kill", "Kill two players within 5 seconds of each other."),
    WARLORDS_SUPER_SOAKER(AchievementGameType.WARLORDS, 5, "Super Soaker", "Shoot a Water Bolt that simultaneously lands a killing blow on an enemy and heals a teammate that had less than 75% health remaining."),
    WARLORDS_SURPRISE_ATTACK(AchievementGameType.WARLORDS, 5, "Surprise Attack", "Get a kill at least 50 blocks away with Flame Burst."),
    HOUSING_JOIN_FRIEND(AchievementGameType.HOUSING, 5, "BFFs", "Join a Friends home."),
    HOUSING_RECIEVE_COOKIE(AchievementGameType.HOUSING, 5, "Filling the Cookie Jar", "Receive a cookie."),
    HOUSING_JOIN_YOUTUBE(AchievementGameType.HOUSING, 5, "Youtube Party", "Join a Youtuber's home."),
    HOUSING_NEW_LOOK(AchievementGameType.HOUSING, 5, "New Look", "Change your home's theme."),
    HOUSING_JOIN_RANDOM(AchievementGameType.HOUSING, 5, "Wandering", "Join a Random home."),
    HOUSING_GIVE_COOKIE(AchievementGameType.HOUSING, 5, "Sharing is Caring", "Give someone a cookie."),
    HOUSING_JOIN_STAFF(AchievementGameType.HOUSING, 5, "Staff Hangout", "Join a Staff Members home."),
    HOUSING_MAKE_RESIDENT(AchievementGameType.HOUSING, 5, "A little help from my friends", "Promote someone to Resident in your home."),
    HOUSING_GRAND_OPENING(AchievementGameType.HOUSING, 5, "Grand Opening", "Open your house to the public."),
    HOUSING_BECOME_RESIDENT(AchievementGameType.HOUSING, 5, "Trusted", "Become Resident in another home."),
    HOUSING_JOIN_GUILD(AchievementGameType.HOUSING, 5, "Guild & Chill", "Join a Guild Members home."),
    TNTGAMES_TNT_TAG_DIFFERENTTAGS(AchievementGameType.TNTGAMES, 10, "One for you and for you and for you ...", "Tag 5 different people in a game of TNT Tag"),
    TNTGAMES_WIZARDS_NOGOOD(AchievementGameType.TNTGAMES, 5, "This is no good", "Jump into the void in TNT Wizards"),
    TNTGAMES_TNT_NPCS(AchievementGameType.TNTGAMES, 5, "I know how this works!", "Use every NPC in the lobby to join games"),
    TNTGAMES_SPLEEF_REPULSOR(AchievementGameType.TNTGAMES, 5, "Have Fun", "Use a Repulsor on someone that is in the air"),
    TNTGAMES_WIZARDS_FIRE_WIZARD_EXPLODE(AchievementGameType.TNTGAMES, 15, "Inferno", "Upgrade Fire Wizard Explodeto Level IX"),
    TNTGAMES_SPLEEF_HITS(AchievementGameType.TNTGAMES, 5, "It's raining arrows", "Shoot 30 arrows at other players in a game of Bow Spleef"),
    TNTGAMES_SPLEEF_NOPERKS(AchievementGameType.TNTGAMES, 10, "I don't need any of that", "Win a game of Bow Spleef without using any perks"),
    TNTGAMES_WIZARDS_HURTS(AchievementGameType.TNTGAMES, 10, "Gotcha", "Hit 3 enemies with 1 Wither Skull in TNT Wizards"),
    TNTGAMES_BOW_SPLEEF_REPULSOR_UPGRADE(AchievementGameType.TNTGAMES, 10, "Jedi Master", "Upgrade Bow Spleef Repulsorto level VI"),
    TNTGAMES_PVP_RUN_FLYING(AchievementGameType.TNTGAMES, 15, "I can do that", "Kill someone in PVP Run with your sword while using a Double Jump"),
    TNTGAMES_WIZARDS_TRIPLE(AchievementGameType.TNTGAMES, 10, "1 ... 2 ... 3!", "Get a triple kill in TNT Wizards"),
    TNTGAMES_RUN_POTIONS(AchievementGameType.TNTGAMES, 10, "Sharing is caring", "Splash 100 potions in total on players in TNT Run and PVP Run"),
    TNTGAMES_WIZARDS_THIRTY_KILLS(AchievementGameType.TNTGAMES, 10, "Wand-erful", "Kill 30 players in one gameof TNT Wizards"),
    TNTGAMES_TNT_WINS_IN_A_ROW(AchievementGameType.TNTGAMES, 15, "Conqueror", "Get 5 wins in a row"),
    TNTGAMES_TNT_TAG_BLOWNUP(AchievementGameType.TNTGAMES, 5, "Take me with you!", "Get blown up by someone else's explosion in TNT Tag"),
    TNTGAMES_TNT_TAG_DANGEROUS(AchievementGameType.TNTGAMES, 15, "I like to live dangerously", "Win a game of TNT Tag after being 'IT' in every round"),
    TNTGAMES_PVP_RUN_TRIPLE(AchievementGameType.TNTGAMES, 10, "Make that three", "Kill 3 people within 12 seconds in PVP Run"),
    TNTGAMES_TNT_RUN_NODJS(AchievementGameType.TNTGAMES, 5, "Triumph", "Win a game of TNT Run without using any double jumps"),
    TNTGAMES_PVP_RUN_NODJS(AchievementGameType.TNTGAMES, 10, "I did it", "Win a game of PVP Run without using any double jumps"),
    TNTGAMES_WIZARDS_BLOOD_WIZARD_REGEN(AchievementGameType.TNTGAMES, 15, "Magic's-a-Gathering", "Upgrade Blood Wizard ManaRegen to Level IX"),
    TNTGAMES_TNT_TAG_SNOWBALL(AchievementGameType.TNTGAMES, 5, "Stay away from me", "Hit 'IT' with a snowball in TNT Tag"),
    TNTGAMES_TNT_TAG_TRAVELLER(AchievementGameType.TNTGAMES, 5, "Traveller", "Travel 1,000 blocks in a game of TNT Tag"),
    TNTGAMES_TNT_TAG_AWW(AchievementGameType.TNTGAMES, 15, "Is it over already?", "Win a game of TNT Tag with more than 2 players alive in the last round"),
    TNTGAMES_BOW_SPLEEF_TRIPLE_SHOT_UPGRADE(AchievementGameType.TNTGAMES, 10, "Legolas", "Upgrade Bow Spleef TripleShotto level VI"),
    TNTGAMES_WIZARDS_JUMPER(AchievementGameType.TNTGAMES, 10, "Weeeeeee", "Use 100 Double Jumps in a game of TNT Wizards"),
    TNTGAMES_TNT_RUN_NOMOVE(AchievementGameType.TNTGAMES, 15, "Paralyzed", "Win a game of TNT Run without moving your head"),
    TNTGAMES_SPLEEF_TRIPLE(AchievementGameType.TNTGAMES, 10, "How did that happen?", "Push 3 players at the same time using your Repulsor in Bow Spleef"),
    TNTGAMES_BOW_SPLEEF_DOUBLE_JUMP_UPGRADE(AchievementGameType.TNTGAMES, 10, "Updating OS...", "Upgrade Bow Spleef DoubleJump to level V"),
    TNTGAMES_SPLEEF_SHOTS(AchievementGameType.TNTGAMES, 5, "Machine Gun", "Fire 250 shots in one game of Bow Spleef"),
    TNTGAMES_TNT_TAG_TAGGER(AchievementGameType.TNTGAMES, 5, "Just take it already!", "Pass the TNT to the same person 5 times in 30 seconds in TNT Tag"),
    TNTGAMES_WIZARDS_CAPHELP(AchievementGameType.TNTGAMES, 5, "Capturer", "Help capture 7 points in one game of TNT Wizards"),
    TNTGAMES_WIZARDS_ASSISTANT(AchievementGameType.TNTGAMES, 10, "Assistant", "Get 30 assists in one TNT Wizards game"),
    TNTGAMES_SPLEEF_NOSHOTS(AchievementGameType.TNTGAMES, 10, "My bow is not working!", "Win a game of Bow Spleef without firing any shots"),
    TNTGAMES_TNT_RUN_FIRSTLAYER(AchievementGameType.TNTGAMES, 15, "This looks high", "Win a game of TNT Run being on the first layer"),
    TNTGAMES_TNT_RUN_FIRST_WIN(AchievementGameType.TNTGAMES, 5, "Unbroken sprinting", "Win a game of TNT Run"),
    TNTGAMES_TNT_RUN_NO_SPRINTING(AchievementGameType.TNTGAMES, 10, "TNT Walk", "Win TNT Run without sprinting"),
    TNTGAMES_SPLEEF_EXHAUSTED(AchievementGameType.TNTGAMES, 5, "Exhausted", "Win a game of Bow Spleef with no perk uses left"),
    TNTGAMES_PVP_RUN_MANYKILLS(AchievementGameType.TNTGAMES, 15, "There is not enough room for all of us!", "Kill 10 Players in a game of PVP Run"),
    TNTGAMES_TNT_PRESTIGE(AchievementGameType.TNTGAMES, 15, "2fancy4me", "Buy a prestige upgrade"),
    TNTGAMES_TNT_RUN_SHORT(AchievementGameType.TNTGAMES, 10, "We just started ...", "Win a game of TNT Run within 2 minutes"),
    TNTGAMES_TNT_RUN_EFFECTS(AchievementGameType.TNTGAMES, 10, "Ineffective", "Win a game of TNT Run while having Speed and Slowness"),
    TNTGAMES_PVP_RUN_PACIFIST(AchievementGameType.TNTGAMES, 10, "Pacifist", "Win a game of PVP Run without hitting anyone"),
    TNTGAMES_WIZARDS_LEADERBOARD(AchievementGameType.TNTGAMES, 5, "Look at me!", "Get on the Top 3 leaderboards in a TNT Wizards game"),
    TNTGAMES_TNT_TAG_FIRST_WIN(AchievementGameType.TNTGAMES, 5, "Boom boom", "Win a game of TNT Tag"),
    TNTGAMES_TNT_PARKOUR(AchievementGameType.TNTGAMES, 10, "Skilled", "Complete the lobby parkour"),
    TNTGAMES_PVP_RUN_SABOTAGE(AchievementGameType.TNTGAMES, 5, "Sabotage", "Throw a slowness potion at someone in PVP Run"),
    TNTGAMES_PVP_RUN_NOHIT(AchievementGameType.TNTGAMES, 10, "Can't touch this", "Win a game of PVP Run without getting hit"),
    TNTGAMES_PVP_RUN_FIRST_WIN(AchievementGameType.TNTGAMES, 5, "A Dangerous Place", "Win a game of PVP Run"),
    TNTGAMES_TNT_TAG_CLOSE(AchievementGameType.TNTGAMES, 5, "Close Call", "Survive a round in which you had the TNT 7 seconds before blowing up in TNT Tag"),
    TNTGAMES_WIZARDS_HEAL(AchievementGameType.TNTGAMES, 5, "Team Player", "Heal 3 different teammates in one game of TNT Wizards"),
    TNTGAMES_WIZARDS_AWIZARD(AchievementGameType.TNTGAMES, 15, "You're a Wizard", "Get 5 Kills with every Wizard Class in a game of TNT Wizards"),
    TNTGAMES_PVP_RUN_HALFHEARTED(AchievementGameType.TNTGAMES, 10, "Not even close", "Win a game of PVP Run on one heart or lower"),
    TNTGAMES_PVP_RUN_POTIONS(AchievementGameType.TNTGAMES, 10, "Revenge is sweet", "Kill a player while having Slowness from that player's Slowness Potion in PVP Run"),
    TNTGAMES_TNT_RUN_FLYING(AchievementGameType.TNTGAMES, 10, "My wings are working", "Be in the air for 10 seconds before dying in a TNT Run game"),
    TNTGAMES_WIZARDS_LEAD(AchievementGameType.TNTGAMES, 10, "What a victory!", "Win by more than 1,000 points in TNT Wizards"),
    TNTGAMES_TNT_RUN_PURCHASE_POTION(AchievementGameType.TNTGAMES, 5, "Quick Feet", "Purchase a Speed Potion for TNT Run"),
    TNTGAMES_BOW_SPLEEF_FIRST_DOUBLE_JUMP(AchievementGameType.TNTGAMES, 5, "Youngling", "Get your first Bow SpleefDouble Jump upgrade"),
    TNTGAMES_WIZARDS_FIRST_WIN(AchievementGameType.TNTGAMES, 5, "DiamondZ", "Win a game of TNT Wizards"),
    TNTGAMES_TNT_TAG_DM(AchievementGameType.TNTGAMES, 5, "The Finals", "Survive until Deathmatch in TNT Tag"),
    TNTGAMES_PVP_RUN_FISTS(AchievementGameType.TNTGAMES, 10, "Fists of Fury", "Kill an enemy with your fists in PVP Run"),
    TNTGAMES_BOW_SPLEEF_FIRST_WIN(AchievementGameType.TNTGAMES, 5, "Parkour champion", "Win a game of Bow Spleef"),
    PAINTBALL_UNLOCK_HAT(AchievementGameType.PAINTBALL, 5, "Mad Hatter", "Unlock a hat from the store"),
    PAINTBALL_ACTIVATE_KILLSTREAKS(AchievementGameType.PAINTBALL, 10, "Unstoppable", "Activate ten killstreaks"),
    PAINTBALL_ACTIVATE_PLUS_TEN(AchievementGameType.PAINTBALL, 10, "Team Player", "Activate PlusTen three times in a game"),
    PAINTBALL_FIRST_KILL(AchievementGameType.PAINTBALL, 5, "The Starter", "Be the first person to kill someone"),
    PAINTBALL_HACKER(AchievementGameType.PAINTBALL, 5, "Hacker?", "Use the forcefield killstreak twice in a game"),
    PAINTBALL_COMBO(AchievementGameType.PAINTBALL, 10, "Combo", "Activate TripleShot and Strongarmperks at the same time"),
    PAINTBALL_UNLOCK_KILLSTREAKS(AchievementGameType.PAINTBALL, 10, "Specialist", "Unlock ten killstreaks"),
    PAINTBALL_NO_KILLSTREAKS(AchievementGameType.PAINTBALL, 10, "Bare Bones", "Win a game without using any killstreaks"),
    PAINTBALL_LAST_KILL(AchievementGameType.PAINTBALL, 5, "The Finisher", "Be the last person to kill someone"),
    PAINTBALL_ACTIVATE_LEEROY_JENKINS(AchievementGameType.PAINTBALL, 10, "LEEEEROOYYY", "Activate Leeroy Jenkins"),
    PAINTBALL_ADMIN_HAT(AchievementGameType.PAINTBALL, 10, "The Originals", "Unlock the Hypixel and Rezzus hats"),
    ARENA_SPARTACUS(AchievementGameType.ARENA, 10, "Spartacus", "Kill someone with over 1250rating in 2v2"),
    ARENA_NOT_EVEN_CLOSE(AchievementGameType.ARENA, 5, "Not Even Close, Baby!", "Win with 250 or less health remainingwhile being the only one alive in 2v2"),
    ARENA_COOLDOWN(AchievementGameType.ARENA, 10, "Cooldown Specialization ", "Buy all Cooldown Combat Upgrades"),
    ARENA_MAGICAL(AchievementGameType.ARENA, 5, "Magical Shenanigans", "Open the Magical Chest forthe first time"),
    ARENA_POOL(AchievementGameType.ARENA, 5, "Life Pool", "Get the healing buff twice in a single game"),
    ARENA_PIG(AchievementGameType.ARENA, 15, "Lucky Pig!", "Find the Guided Pig 2000in the Magical Chest"),
    ARENA_SMASH(AchievementGameType.ARENA, 5, "Smash!", "Hit 2 players with a single Boulder Toss"),
    ARENA_FLAWLESS(AchievementGameType.ARENA, 5, "Flawless Victory", "Win with at least 2000 health remaining in 2v2"),
    ARENA_UTILITY(AchievementGameType.ARENA, 5, "Utility Training", "Unlock a Utility Skill"),
    ARENA_MELEE(AchievementGameType.ARENA, 10, "Melee Specialization ", "Buy all Melee Combat Upgrades"),
    ARENA_RUNIC(AchievementGameType.ARENA, 5, "Runic Enhancements", "Unlock a Rune in the shop"),
    ARENA_PUNISHER(AchievementGameType.ARENA, 5, "The Punisher", "Get the double damage bufftwice in a single game"),
    ARENA_OVERKILL(AchievementGameType.ARENA, 5, "Overkill", "Deal over 800 damage at once"),
    ARENA_ENERGY(AchievementGameType.ARENA, 10, "Energy Specialization ", "Buy all Energy Combat Upgrades"),
    ARENA_ULTIMATE(AchievementGameType.ARENA, 5, "Ultimate Training", "Unlock an Ultimate Skill"),
    ARENA_HEALTH(AchievementGameType.ARENA, 10, "Health Specialization ", "Buy all Health Combat Upgrades"),
    ARENA_PAIRS(AchievementGameType.ARENA, 5, "Working In Pairs", "Win with you and your partner alive"),
    ARENA_SUPPORT(AchievementGameType.ARENA, 5, "Support Training", "Unlock a Support Skill"),
    ARENA_TOTEM_DESTROYER(AchievementGameType.ARENA, 5, "Totem Destroyer", "Destroy a healing totem"),
    ARENA_OFFENSIVE(AchievementGameType.ARENA, 5, "Offensive Training", "Unlock an Offensive Skill"),
    ARENA_NOT_TODAY(AchievementGameType.ARENA, 5, "Not today", "Destroy an enemy barricade"),
    ARCADE_GOTTA_CATCH_THEM_ALL(AchievementGameType.ARCADE, 10, "Gotta catch them all!", "Have 1 minute of powerups left at the end of an Ender Spleef game"),
    ARCADE_CREEPER_ATTACK_SURVIVAL(AchievementGameType.ARCADE, 10, "Creeeep", "Survive Creeper Attack without dying"),
    ARCADE_OVERPOWERED(AchievementGameType.ARCADE, 5, "Overpowered", "Have a Triple Shot and a Big Shot active at the same time in Ender Spleef"),
    ARCADE_RPG_16_ROCKET_PIG(AchievementGameType.ARCADE, 10, "Oink.", "Kill 3 or more players withone rocket pig"),
    ARCADE_WORLD_ECONOMICS(AchievementGameType.ARCADE, 5, "World Economics", "Exchange your coins for another minigame"),
    ARCADE_CANT_HIDE_FROM_ME(AchievementGameType.ARCADE, 5, "Can't hide from me!", "Kill the last animal"),
    ARCADE_FARM_HUNT_DISGUISE(AchievementGameType.ARCADE, 5, "Farm Animal", "Survive a game of Farm Huntdisguised as an animal"),
    ARCADE_OVER_HERE(AchievementGameType.ARCADE, 10, "I'm over here!", "Use all five of your fireworks in Farm Hunt"),
    ARCADE_GIDDY_UP_HORSEY(AchievementGameType.ARCADE, 10, "Giddy up horsey!", "Win a game of Farm Hunt as a horse"),
    ARCADE_DRAGONTAMER(AchievementGameType.ARCADE, 10, "DragonTamer", "Kill 7 people in one Dragon Wars game while riding a Dragon"),
    ARCADE_SHOOTING_RANGE_EXPLOSIVE_ARROW(AchievementGameType.ARCADE, 10, "Explosive Archer", "Kill 5 or more targets withone Explosive Arrow"),
    ARCADE_NO_MUTINY_TODAY(AchievementGameType.ARCADE, 10, "No mutiny today", "Obtain a score of at least 70 in Bounty Hunters"),
    ARCADE_CREEPER_ATTACK_IRON_GOLEM(AchievementGameType.ARCADE, 5, "Pay the Iron Price", "Kill an Iron Golem in Creeper Attack"),
    ARCADE_NO_MERCY(AchievementGameType.ARCADE, 5, "No Mercy", "Kill a player zombie with a knife in Blocking Dead"),
    ARCADE_THROW_OUT_POWERUP_KILL(AchievementGameType.ARCADE, 5, "Superman", "Knock a player out using the Megapunchpowerup in Throw Out"),
    ARCADE_PTB_RIDE_BAT(AchievementGameType.ARCADE, 5, "Batman", "Ride a bat in Punch the Bat"),
    ARCADE_TEAM_SLAYER(AchievementGameType.ARCADE, 5, "Complete Elimination", "Deliver the final blow to all members of an enemy team in a game of Mini Walls"),
    ARCADE_HOEHOEHOE_SCORE(AchievementGameType.ARCADE, 10, "Spam Clicker", "Score 150 points in HoeHoeHoe"),
    ARCADE_CREEPER_ATTACK_WAVES(AchievementGameType.ARCADE, 10, "Hssssss", "Survive until wave 20 in Creeper Attack"),
    ARCADE_AVALANCE_WAVES(AchievementGameType.ARCADE, 10, "Avalanche!", "Survive 18 waves in Avalanche"),
    ARCADE_PARTY_GAMES_STARS(AchievementGameType.ARCADE, 10, "Partier", "Finish with 20 or more starsin Party Games"),
    ARCADE_TRAMPOLINIO_RED_WOOL(AchievementGameType.ARCADE, 5, "Bouncy Bounce", "Collect a red wool in Trampolinio"),
    ARCADE_DRAGON_SLAYER(AchievementGameType.ARCADE, 10, "Dragon Slayer", "Get 25 kills in one game of Dragon Wars"),
    ARCADE_UNTOUCHABLE(AchievementGameType.ARCADE, 5, "Untouchable", "Win a Farm Hunt game with full health"),
    ARCADE_LONE_SURVIVOR(AchievementGameType.ARCADE, 10, "Lone Survivor", "Win a game of Blocking Dead as the last survivor"),
    ARCADE_ANIMAL_SLAUGHTER(AchievementGameType.ARCADE, 10, "Inhumane", "Murder 50 animals in Animal Slaughter"),
    ARCADE_PROFESSIONAL_MOWER(AchievementGameType.ARCADE, 5, "Professional Mower", "Gain 250 points in Lawn Moower"),
    ARCADE_SAVAGE(AchievementGameType.ARCADE, 10, "Savage", "Kill a hunter in Farm hunt"),
    ARCADE_DRAGON_KILLER(AchievementGameType.ARCADE, 10, "Khaleesi", "Kill a player while riding adragon in Dragon Wars"),
    ARCADE_PIG_FISHING_SUPER_BACON(AchievementGameType.ARCADE, 5, "BACON!!!", "Capture a Super Bacon in Pig Fishing"),
    ARCADE_CREEPER_ATTACK_UPGRADES(AchievementGameType.ARCADE, 10, "Getting an Upgrade", "Fully upgrade your sword, bow,and armor in Creeper Attack"),
    ARCADE_BOUNTY_HUNTER_TARGET_KILLER(AchievementGameType.ARCADE, 5, "Fight Like a Man", "Kill your target in Bounty Hunterwith your sword"),
    ARCADE_WOOPS_DIDNT_MEAN_TO(AchievementGameType.ARCADE, 5, "Woops, didn't mean to", "Punch someone during the minigame Avalanche"),
    ARCADE_MINI_HUNTER(AchievementGameType.ARCADE, 5, "Mini Hunter", "Deliver the final blow to 2 Mini Withers in a game of Mini Walls"),
    ARCADE_LEGENDARY(AchievementGameType.ARCADE, 10, "LEGENDARY", "Get a high enough score for Diamond Rain in Build Battle"),
    GINGERBREAD_NEW_STYLE(AchievementGameType.GINGERBREAD, 5, "New Style", "Unlock a kart skin"),
    GINGERBREAD_GET_HIT_BY_ME(AchievementGameType.GINGERBREAD, 5, "Get hit!", "Hit a player with any projectile"),
    GINGERBREAD_GETTING_GOOD(AchievementGameType.GINGERBREAD, 5, "Getting good!", "Complete a race"),
    GINGERBREAD_IS_THIS_SURVIVAL_GAMES(AchievementGameType.GINGERBREAD, 5, "Is this Survival Games?", "Hit 5 players with the \"Notched Sword\" in 1 race"),
    GINGERBREAD_TRYHARDER(AchievementGameType.GINGERBREAD, 5, "Tryharder!", "Win a trophy without using any items"),
    GINGERBREAD_NEVER_LUCKY(AchievementGameType.GINGERBREAD, 5, "Never Lucky", "Get hit by more than 1 Blue Torpedo in 1 race"),
    GINGERBREAD_GETTIN_PAID(AchievementGameType.GINGERBREAD, 5, "Gettin' Paid", "Win a Pink Part as a gaming reward"),
    GINGERBREAD_COINS_PLEASE(AchievementGameType.GINGERBREAD, 5, "Coins Please", "Use the junkyard"),
    GINGERBREAD_IM_LUCKY(AchievementGameType.GINGERBREAD, 5, "I'm Lucky", "Use the part roller"),
    GINGERBREAD_TASTE_MY_BANANA(AchievementGameType.GINGERBREAD, 5, "BA NA NA NA NA", "Hit a player with a banana"),
    SUPERSMASH_GENCLUCK_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "General Cluck Challenge", "Kill every enemy hero at least once with your Chicken Army"),
    SUPERSMASH_PUG_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Pug Challenge", "Kill at least 2 enemies with the same Sonic Bark"),
    SUPERSMASH_YOUNG_APPRENTICE(AchievementGameType.SUPERSMASH, 10, "Young Apprentice, You are not", "Unlock a Master Skin for a Hero"),
    SUPERSMASH_SHOOP_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Shoop Challenge", "Kill at least 3 enemies with a single FIRIN' MAH LAZOR"),
    SUPERSMASH_REACH_STARS(AchievementGameType.SUPERSMASH, 15, "Reaching the Stars", "Prestige a Hero 5 times"),
    SUPERSMASH_REACH_SKY(AchievementGameType.SUPERSMASH, 10, "Reaching the Sky", "Prestige a Hero"),
    SUPERSMASH_TINMAN_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Tinman Challenge", "Kill an enemy hero with your Overload Passive"),
    SUPERSMASH_SPOODERMAN_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Spooderman Challenge", "Kill an enemy hero with a Spooder Kick just after hitting them with a Web Shot from 15 blocks away"),
    SUPERSMASH_BOTMON_VS_SPOODERMAN(AchievementGameType.SUPERSMASH, 5, "Botmon Versus Spooderman!", "Kill Botmon while using Spooderman, or vice-versa"),
    SUPERSMASH_FROSTMAGE_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Cryomancer Challenge", "Slow 2 enemy heroes with a single Frostbolt"),
    SUPERSMASH_DOMINATION(AchievementGameType.SUPERSMASH, 5, "Domination", "Kill 6 enemy heroes in one game"),
    SUPERSMASH_MARAUDER_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Marauder Challenge", "Hit 3 or more enemy heroes with a single Grip"),
    SUPERSMASH_TWO_FOR_ONE(AchievementGameType.SUPERSMASH, 10, "Two For One", "Smash 2 or more enemy heroes with the same skill"),
    SUPERSMASH_SECOND_ROUND(AchievementGameType.SUPERSMASH, 5, "Second Round!", "Pick up a Smash Crystal within 5 seconds after using your Smash"),
    SUPERSMASH_KARAKOT_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Karakot Challenge", "Kill 2 enemy heroes while in True Power mode"),
    SUPERSMASH_BOTMON_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Botmon Challenge", "Hit the same hero 3 times with your Botmobile before your crystal ability ends"),
    SUPERSMASH_BULK_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Bulk Challenge", "Hit 3 enemy heroes simultaneously with any of Bulk's abilities"),
    SUPERSMASH_TOO_EASY(AchievementGameType.SUPERSMASH, 5, "Too Easy", "Win a game without using a Smash ability"),
    SUPERSMASH_VOID_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Void Crawler Challenge", "Kill 2 enemy heroes during a single Shadow Fury"),
    SUPERSMASH_GET_OVER_HERE(AchievementGameType.SUPERSMASH, 5, "Get Over Here!", "Pull an enemy hero back from the void using Marauder's Grip"),
    SUPERSMASH_CAKE_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Cake Monster Challenge", "Kill an enemy hero with Defecake"),
    SUPERSMASH_SUPREMACY(AchievementGameType.SUPERSMASH, 5, "Supremacy", "Win a game without dying once"),
    SUPERSMASH_NEED_ALL(AchievementGameType.SUPERSMASH, 5, "I NEED THEM ALL!", "Find 2 Smash Crystals in a game"),
    SUPERSMASH_EXPERIENCE_EXPRESS(AchievementGameType.SUPERSMASH, 5, "Experience Express", "Use an EXP Booster"),
    SUPERSMASH_TEAMWORK(AchievementGameType.SUPERSMASH, 5, "Teamwork at its Finest", "Win a Team game with 8 kills total without losing a life"),
    SUPERSMASH_SKULLFIRE_CHALLENGE(AchievementGameType.SUPERSMASH, 5, "Skullfire Challenge", "Hit an enemy hero with every bullet in your clip without missing"),
    SUPERSMASH_THE_PEAK(AchievementGameType.SUPERSMASH, 10, "The Peak", "Reach level 20 with a hero"),
    MURDERMYSTERY_KALI_FAVOR(AchievementGameType.MURDERMYSTERY, 10, "Kali's Favourite", "Raise your favour with Kali to 10 or above on Ancient Tomb"),
    MURDERMYSTERY_BLESSING_AND_CURSE(AchievementGameType.MURDERMYSTERY, 5, "Mixed Messages", "Receive a blessing and a curse from Kali in the same game on Ancient Tomb"),
    MURDERMYSTERY_KILL_MURDERER_AS_LAST_ALIVE(AchievementGameType.MURDERMYSTERY, 15, "Close Enough", "Be the last one alive and kill the murderer"),
    MURDERMYSTERY_PICKUP_GOLD(AchievementGameType.MURDERMYSTERY, 5, "That Was Easy", "Collect 10 gold in the first minute of the game"),
    MURDERMYSTERY_WIN_SURVIVOR_DUE_TO_TIME(AchievementGameType.MURDERMYSTERY, 5, "Catch Me If You Can", "As innocent, win because the murderer's time ran out"),
    MURDERMYSTERY_BOW_KILLSTREAK(AchievementGameType.MURDERMYSTERY, 10, "The Arrow Streak", "Get 5 kills in a row with a bow"),
    MURDERMYSTERY_THIRTY_GOLD_PICKED_UP(AchievementGameType.MURDERMYSTERY, 10, "Gold Hunter", "Pick up 30 gold in one game"),
    MURDERMYSTERY_BE_THE_HERO(AchievementGameType.MURDERMYSTERY, 5, "Saving The Day", "Be the hero of the game"),
    MURDERMYSTERY_SHOOT_THROWN_KNIFE(AchievementGameType.MURDERMYSTERY, 15, "Sniper", "Shoot a thrown knife with a bow"),
    MURDERMYSTERY_THREE_ARROWS(AchievementGameType.MURDERMYSTERY, 10, "Lock And Load", "As innocent, have three arrows at once"),
    MURDERMYSTERY_SWORD_KILL_LONG_RANGE(AchievementGameType.MURDERMYSTERY, 10, "Bullseye", "Nail a sword throw from over 30 blocks"),
    MURDERMYSTERY_RIDE_MONORAIL(AchievementGameType.MURDERMYSTERY, 5, "This Isn't A Funfair ... Maybe", "Ride the monorail"),
    MURDERMYSTERY_BOW_KILL_ON_DETECTIVE(AchievementGameType.MURDERMYSTERY, 15, "Humiliation", "As murderer, use bow and arrow to kill the detective"),
    MURDERMYSTERY_WIN_INNO_MONORAIL(AchievementGameType.MURDERMYSTERY, 15, "Wicked Ride", "Be the last innocent alive, and win the game while riding the monorail."),
    MURDERMYSTERY_SPECIAL_TWO_IN_A_ROW(AchievementGameType.MURDERMYSTERY, 10, "I Am Special", "Be Murderer or Detective two games in a row"),
    MURDERMYSTERY_SECRET_CHAMBER(AchievementGameType.MURDERMYSTERY, 15, "We're Set", "Find and enter the combination to open the secret chamber on Gold Rush"),
    MURDERMYSTERY_WIN_AS_MURDERER_SHORT_TIME(AchievementGameType.MURDERMYSTERY, 5, "Calculated", "As murderer, win with less than 15 seconds remaining"),
    MURDERMYSTERY_PLAY_BOTH_GAMES(AchievementGameType.MURDERMYSTERY, 5, "Game-ception", "Play both of the Arcade Games on Cruise Ship"),
    MURDERMYSTERY_LONGRANGE_SHOT(AchievementGameType.MURDERMYSTERY, 15, "Sharpshooter", "As detective, shoot the murderer from over 30 blocks"),
    MURDERMYSTERY_RETURN_FROM_DEAD_WIN(AchievementGameType.MURDERMYSTERY, 15, "Beyond The Grave", "Return from the dead and win the game on Ancient Tomb"),
    MURDERMYSTERY_WIN_MURDERER_FELL_IN_TRAP(AchievementGameType.MURDERMYSTERY, 10, "Don't Go There", "Win a game due to the murderer falling into a trapdoor"),
    MURDERMYSTERY_NO_GOLD_PICKUP(AchievementGameType.MURDERMYSTERY, 15, "No Money, No Problems", "As innocent, survive until the end of the game, while the murderer is still alive, without having collected any gold"),
    MURDERMYSTERY_KILL_IN_RAPID_TRANSPORT(AchievementGameType.MURDERMYSTERY, 10, "Totally Tubulur", "Kill another player whilst using Rapid Transport on Transport"),
    MURDERMYSTERY_SURVIVE_STORM_ON_TOP(AchievementGameType.MURDERMYSTERY, 10, "Storm Chaser", "Survive the storm without going to the lower deck on Cruise Ship"),
    MURDERMYSTERY_BLOCK_WITH_BARRIER(AchievementGameType.MURDERMYSTERY, 10, "I Am Your Shield", "Deploy a barrier that blocks an arrow or thrown sword on Transport"),
    MURDERMYSTERY_ALL_DIRECTIONS(AchievementGameType.MURDERMYSTERY, 5, "Well Traveled", "Use the Rapid Transport to visit all 4 destinations in the same game on Transport"),
    MURDERMYSTERY_MURDERER_BOW_KILLS(AchievementGameType.MURDERMYSTERY, 10, "Wrong Weapon", "As murderer, get 3 kills in one game with a bow"),
    MURDERMYSTERY_FIVE_CURSES(AchievementGameType.MURDERMYSTERY, 10, "It's Time To Stop", "Receive 5 different curses from Kali in the same game on Ancient Tomb"),
    MURDERMYSTERY_WIN_WHILE_INVINCIBLE(AchievementGameType.MURDERMYSTERY, 5, "Can't Touch This", "Win a game while being invincible"),
    MURDERMYSTERY_FIRST_SHOT_HIT(AchievementGameType.MURDERMYSTERY, 10, "On Point", "As innocent, kill the murderer with your first bow shot"),
    MURDERMYSTERY_MURDERER_FIRST_KILL(AchievementGameType.MURDERMYSTERY, 15, "Clean Round", "Kill the murderer before anybody has died"),
    MURDERMYSTERY_THREE_KNIFE_THROW_KILLS(AchievementGameType.MURDERMYSTERY, 10, "Assassin", "As murderer, kill 3 players in one game by throwing your knife at them"),
    MURDERMYSTERY_KILL_MURDERER_AFTER_KILL(AchievementGameType.MURDERMYSTERY, 10, "Caught In The Act", "Kill the murderer within three seconds after they killed someone"),
    MURDERMYSTERY_HIT_BY_SWORD_WHILE_INVINC(AchievementGameType.MURDERMYSTERY, 5, "You Tried", "Get hit in melee while you are invincible"),
    MURDERMYSTERY_DRINK_MANY_POTIONS(AchievementGameType.MURDERMYSTERY, 10, "Quenchy", "Drink sixteen potions in one game"),
    MURDERMYSTERY_KILL_MURDERER_WHILE_BLINDED(AchievementGameType.MURDERMYSTERY, 15, "Blind Justice", "Kill the murderer while being blinded"),
    MURDERMYSTERY_KILL_WHILE_MONORAIL(AchievementGameType.MURDERMYSTERY, 10, "You Did Not See That Coming!", "Kill a player while riding the monorail"),
    MURDERMYSTERY_PLAY_GAME_IN_LOBBY(AchievementGameType.MURDERMYSTERY, 5, "Well, That's Cool", "Play one of the minigames in the lobby"),
    MURDERMYSTERY_SOLDIERS_ELIMINATED(AchievementGameType.MURDERMYSTERY, 5, "History Erased", "Witness the destruction of all Kali's Soldiers on Ancient Tomb"),
    MURDERMYSTERY_KILL_DETECTIVE_FAST(AchievementGameType.MURDERMYSTERY, 10, "Not Today", "As murderer, kill the detective within 15 seconds of receiving your weapon"),
    MURDERMYSTERY_KILL_ON_HORSE(AchievementGameType.MURDERMYSTERY, 10, "It's High Noon", "Kill the murderer as an innocent, or any innocent as the murderer with a bow whilst riding a horse on Gold Rush"),
    MURDERMYSTERY_CLEAR_CACTI(AchievementGameType.MURDERMYSTERY, 5, "Cacti Cleared", "Help clear all the Cacti in one game on Gold Rush"),
    MURDERMYSTERY_KILLSTREAK(AchievementGameType.MURDERMYSTERY, 10, "Slice N Dice", "As murderer, get five kills in five seconds"),
    SKYCLASH_WHATS_NEXT(AchievementGameType.SKYCLASH, 10, "What's next?", "Max out a Card"),
    SKYCLASH_BAD_KARMA(AchievementGameType.SKYCLASH, 5, "Bad Karma", "Get a kill after you died"),
    SKYCLASH_ADDICTED(AchievementGameType.SKYCLASH, 5, "Addicted", "Purchase your first Card Pack"),
    SKYCLASH_POWERSPIKE(AchievementGameType.SKYCLASH, 5, "Powerspike!", "Open an Enderchest"),
    SKYCLASH_ANVIL_KILL(AchievementGameType.SKYCLASH, 10, "An Kill", "Kill an enemy with a falling Anvil"),
    SKYCLASH_MAX_POWER(AchievementGameType.SKYCLASH, 15, "Maximum Power", "Create a Class with fully maxed Cards and Kit"),
    SKYCLASH_HAPPY_LITTLE_ACHIEVEMENT(AchievementGameType.SKYCLASH, 5, "Happy little achievement", "Kill a player using a Painting or a Happy Little Tree"),
    SKYCLASH_ARE_YOU_CRAZY(AchievementGameType.SKYCLASH, 5, "Are you crazy?", "Knock off 5 or more players in a single game"),
    SKYCLASH_VOID_KILLER(AchievementGameType.SKYCLASH, 10, "I made some people mad", "Throw 1000 players in the void"),
    SKYCLASH_GOLDEN_ONE(AchievementGameType.SKYCLASH, 10, "The Golden One", "Find the entire El Dorado set while playing with the Treasure Hunter kit"),
    SKYCLASH_NO_CHEST(AchievementGameType.SKYCLASH, 10, "No Chest Challenge", "Win a Solo game using the No Chest Challenge Card"),
    SKYCLASH_FLYING(AchievementGameType.SKYCLASH, 5, "Flying!", "Knock someone into the void using the One Punch Bow"),
    SKYCLASH_NEW_PASSIVE(AchievementGameType.SKYCLASH, 10, "New Passive!", "Master a Kit"),
    SKYCLASH_SHARP_JUSTICE(AchievementGameType.SKYCLASH, 5, "Sharpened Justice", "Find a Sharpness II Sword of Justice in a chest"),
    SKYCLASH_SKYCLASH_EXPERT(AchievementGameType.SKYCLASH, 5, "SkyClash Expert", "Get 100 kills with 5 different kits"),
    SKYCLASH_UHC_CHALLENGE(AchievementGameType.SKYCLASH, 10, "UHC Challenge", "Win a Solo game using the UHC Challenge Card"),
    SKYCLASH_HEROIC_CHARGE(AchievementGameType.SKYCLASH, 10, "Heroic Charge", "Kill a whole team by yourself in Team War"),
    SKYCLASH_NO_ALCHEMY(AchievementGameType.SKYCLASH, 10, "Disallowed alchemy", "Win a game without using any kind of potion"),
    SKYCLASH_BOO(AchievementGameType.SKYCLASH, 10, "Boo!", "Get a kill within 3 seconds of using an Ender Pearl"),
    SKYCLASH_ASSASSINATION(AchievementGameType.SKYCLASH, 5, "Assassination", "Kill someone while you're invisible"),
    SKYCLASH_MY_PLAYSTYLE(AchievementGameType.SKYCLASH, 5, "This is my playstyle!", "Use the Class Editor for the first time"),
    SKYCLASH_ARCHER_CHALLENGE(AchievementGameType.SKYCLASH, 10, "Archer Challenge", "Win a Solo game using the Archer Challenge Card"),
    SKYCLASH_STAY(AchievementGameType.SKYCLASH, 5, "Stay where you are!", "Kill a player while they are on their starting island"),
    SKYCLASH_KAWAII_PANTS(AchievementGameType.SKYCLASH, 10, "K-k-k-kawaii!!", "Find the Cute Pants 10 times"),
    SKYCLASH_MISSING_APPLE(AchievementGameType.SKYCLASH, 5, "Where did you find that? ", "Eat an Enchanted Golden Apple"),
    SKYCLASH_DREAM_TEAM(AchievementGameType.SKYCLASH, 5, "Dream Team", "Win a Team War game with all teammates alive"),
    SKYCLASH_KILL_SECURED(AchievementGameType.SKYCLASH, 5, "Kill Secured", "Get a killing blow on a player over 50 blocks away"),
    SKYCLASH_RUSHER(AchievementGameType.SKYCLASH, 5, "Rusher", "Be the first person to open an Ender Chest in a game"),
    SKYCLASH_GREATMAN(AchievementGameType.SKYCLASH, 10, "I am Greatman!", "Wear a full set of Greatman's armor"),
    SKYCLASH_IM_A_BETTER_WIZARD(AchievementGameType.SKYCLASH, 10, "I'm an even better Wizard!", "Kill 2 or more players with one Fireball"),
    SKYCLASH_GOD_OF_MONSTERS(AchievementGameType.SKYCLASH, 5, "God of monsters", "Spawn a total of 1,000 mobs"),
    SKYCLASH_TRAINED_WELL(AchievementGameType.SKYCLASH, 10, "I trained it well!", "Kill someone with your own Ender Dragon"),
    SKYCLASH_SKYMON_GO(AchievementGameType.SKYCLASH, 5, "Is this Skymon Go?", "Win a game with 3 different Monster Cards in your Class"),
    SKYCLASH_REST_IN_PEPPERONI(AchievementGameType.SKYCLASH, 5, "Rest in Pepperoni", "Kill 3 players in the same game with The Spoon"),
    SKYCLASH_ENDLESS_QUIVER(AchievementGameType.SKYCLASH, 5, "Endless Quiver", "Shoot a total of 10,000 arrows"),
    SKYCLASH_LIGHTWEIGHT(AchievementGameType.SKYCLASH, 5, "Lightweight feather", "Win a game with the Winged Boots equipped"),
    SKYCLASH_IM_A_WIZARD(AchievementGameType.SKYCLASH, 5, "I'm a Wizard!", "Find a Fireball and use it"),
    SKYWARS_PEACEMAKER(AchievementGameType.SKYWARS, 10, "Peacemaker", "Win a game without killing anyone"),
    SKYWARS_SIEGE(AchievementGameType.SKYWARS, 10, "The siege", "Get the final kill of a game in your spawn island"),
    SKYWARS_SHINY_STUFF(AchievementGameType.SKYWARS, 10, "Shiny Stuff", "Wear a full Diamond set of armor"),
    SKYWARS_MOB_SPAWNER(AchievementGameType.SKYWARS, 10, "Mob Spawner", "Spawn a mob"),
    SKYWARS_BALLER(AchievementGameType.SKYWARS, 10, "Baller!", "Get 2 snowball kills in one game"),
    SKYWARS_NOW_IM_ENCHANTED(AchievementGameType.SKYWARS, 10, "Now I'm Enchanted!", "Enchant a Diamond Sword"),
    SKYWARS_ENDERDRAGON(AchievementGameType.SKYWARS, 10, "Enderdragon", "Play a Game with an Enderdragon"),
    SKYWARS_MAX_PERK(AchievementGameType.SKYWARS, 10, "Max Perk!", "Max out a tiered perk"),
    SKYWARS_KILL_STREAK(AchievementGameType.SKYWARS, 10, "Kill Streak", "Get 5 kills in 15 seconds"),
    SKYWARS_LUCKY_CHARM(AchievementGameType.SKYWARS, 15, "Money well spent!", "Get Lucky Charm to level 20"),
    SKYWARS_SOLO_WARRIOR(AchievementGameType.SKYWARS, 10, "Solo warrior", "Win a Mega game while joining without a party"),
    SKYWARS_WHO_NEEDS_TEAMMATES(AchievementGameType.SKYWARS, 5, "Who needs teammates?", "Summon a skeleton and a blaze"),
    SKYWARS_LUCKY_SOULS(AchievementGameType.SKYWARS, 5, "Lucky Souls", "Obtain 5 Mega Perks"),
    SKYWARS_TOUCH_OF_DEATH(AchievementGameType.SKYWARS, 10, "Touch of Death!", "Knock someone into the void with a single punch"),
    SKYWARS_MEGA_WARRIOR(AchievementGameType.SKYWARS, 10, "Mega Warrior", "Kill 20 players in 1 mega game"),
    SKYWARS_TROLOL(AchievementGameType.SKYWARS, 5, "Trolololololol", "Win a game with the Troll Kit"),
    SKYWARS_GAPPLE(AchievementGameType.SKYWARS, 10, "Gapple!", "Eat a Golden Apple"),
    SKYWARS_NICK_CAGE(AchievementGameType.SKYWARS, 10, "Nick Cage", "Unlock Nicolas Cage"),
    SKYWARS_WELL_WELL(AchievementGameType.SKYWARS, 10, "Well, well", "Use the Soul Well"),
    SKYWARS_NO_CHEST_CHALLENGE(AchievementGameType.SKYWARS, 10, "No Chest Challenge", "Win a Mega game without opening any chest"),
    SKYWARS_GONE_FISHING(AchievementGameType.SKYWARS, 10, "Gone Fishing", "Get a Fishing Rod kill"),
    SKYWARS_FAST_AND_FURIOUS(AchievementGameType.SKYWARS, 10, "2Fast3Furious", "Get a kill in the first 10 seconds of the game"),
    SKYWARS_FEAR_ME(AchievementGameType.SKYWARS, 10, "Fear me mortals", "Max out a Mega Kit"),
    SKYWARS_GOTCHA(AchievementGameType.SKYWARS, 10, "Gotcha!", "Kill someone while you have less than 1 heart left"),
    SKYWARS_FISTS_OF_FURY(AchievementGameType.SKYWARS, 10, "Fist of Fury!", "Kill someone with your bare hands"),
    SKYWARS_LEGENDARY(AchievementGameType.SKYWARS, 10, "LEGENDARY!!!", "Find a Legendary in the Soul Well"),
    SKYWARS_OPEN_CHEST(AchievementGameType.SKYWARS, 5, "3; 2; 1; GO", "Be the first player to open a chest"),
    SKYWARS_SPEED_RUNNER(AchievementGameType.SKYWARS, 10, "Speed Runner", "Win a Mega game before the last chest refill"),
    SKYWARS_HASTA_LA_VISTA(AchievementGameType.SKYWARS, 5, "Hasta la Vista", "Punch someone into the void with a punch bow"),
    SKYWARS_SNIPER(AchievementGameType.SKYWARS, 10, "Sniper", "Get 30 bow hits in one game"),
    SKYWARS_SPEED_RUN(AchievementGameType.SKYWARS, 10, "Speed Run", "Win a Ranked game in less than a minute"),
    SKYWARS_PORTAL_GAME(AchievementGameType.SKYWARS, 5, "Is this a Portal game?", "Obtain a stack of ender pearls"),
    SKYWARS_WELL_DESERVED(AchievementGameType.SKYWARS, 5, "Well deserved", "Gain a reward from a Ranked Season"),
    SKYWARS_TEAMWORK(AchievementGameType.SKYWARS, 5, "Teamwork", "Win a Mega game with all your teammates alive"),
    VAMPIREZ_PURCHASE_BLOOD(AchievementGameType.VAMPIREZ, 5, "Cash4Blood", "Purchase Blood from the shop"),
    VAMPIREZ_PURCHASE_GOLD(AchievementGameType.VAMPIREZ, 5, "Coins4Gold", "Purchase Gold from the shop"),
    VAMPIREZ_BLOOD(AchievementGameType.VAMPIREZ, 5, "Bloodthirsty", "Have 150 Blood at once"),
    VAMPIREZ_PURCHASE_FOOD(AchievementGameType.VAMPIREZ, 5, "Not the Survival Games", "Purchase food from the Gold Shop"),
    VAMPIREZ_SOLE_SURVIVOR(AchievementGameType.VAMPIREZ, 10, "Last Man Standing", "Be the last remaining Survivor"),
    VAMPIREZ_VAMPIRE_FANG_KILL(AchievementGameType.VAMPIREZ, 5, "The Original", "Kill a Survivor with The Original Fang"),
    VAMPIREZ_VAMPIRE_KILLS_ONE_ROUND(AchievementGameType.VAMPIREZ, 10, "Vampire Slayer", "Kill 15 Vampires in one game"),
    VAMPIREZ_PURCHASE_ARMOR(AchievementGameType.VAMPIREZ, 5, "Fits Like a Glove", "Purchase armor from the Gold Shop"),
    VAMPIREZ_DONT_NEED_IT(AchievementGameType.VAMPIREZ, 15, "Don't need it!", "Win a game as a Human without using the shop"),
    VAMPIREZ_PURCHASE_SWORD(AchievementGameType.VAMPIREZ, 5, "Dangerous to Go Alone", "Purchase a sword from the Gold Shop"),
    VAMPIREZ_VAMPIRE_SHOP(AchievementGameType.VAMPIREZ, 5, "Vampiric Mutant", "Purchase something from the Blood Shop"),
    VAMPIREZ_POTIONS(AchievementGameType.VAMPIREZ, 5, "POTIONS!", "Drink 20 Potions as a Human in a single game"),
    VAMPIREZ_WIZARD(AchievementGameType.VAMPIREZ, 5, "Wizard", "Use 5 holy books in a single game as a Human"),
    VAMPIREZ_KILL_ZOMBIES(AchievementGameType.VAMPIREZ, 10, "Zombie Killer", "Kill 35 Zombies in one game"),
    VAMPIREZ_UNDEFEATABLE(AchievementGameType.VAMPIREZ, 10, "Undefeatable!", "Purchase a full set of God Armor and a God Sword as a Human"),
    VAMPIREZ_CHEST_HUNTER(AchievementGameType.VAMPIREZ, 10, "Chest Hunter", "Find 3 loot chests"),
    VAMPIREZ_GOLD(AchievementGameType.VAMPIREZ, 10, "Gold Digger", "Have 1000 Gold at once"),
    VAMPIREZ_LAST_CHANCE(AchievementGameType.VAMPIREZ, 15, "Last Chance", "Win the game as the last remaining Human"),
    VAMPIREZ_FIRST_WAVE_KILL(AchievementGameType.VAMPIREZ, 5, "Black Friday", "Kill a Survivor in the first round"),
    VAMPIREZ_ZOMBIE_SLAYER(AchievementGameType.VAMPIREZ, 10, "Zombie Slayer", "Kill 100 Zombies in a single game"),
    VAMPIREZ_SURVIVOR_KILLS_ONE_ROUND(AchievementGameType.VAMPIREZ, 10, "Bloody Bulldozer", "Kill 10 Survivors in one game"),
    VAMPIREZ_CLOSE_CALL(AchievementGameType.VAMPIREZ, 10, "Close Call", "Kill a Vampire while on half a heart"),
    VAMPIREZ_ZOMBIE_WHISPERER(AchievementGameType.VAMPIREZ, 5, "Zombie Whisperer", "Kill a survivor with a Baby Zombie"),
    WALLS3_WHATS_THE_BIG_IDEA(AchievementGameType.WALLS3, 10, "What's the big idea!?", "Final kill an enemy after splashing them with a regen potion as Phoenix, before the potion expires"),
    WALLS3_READY_SET_BOOM(AchievementGameType.WALLS3, 10, "Ready.. Set.. Boom!", "Collect 2 stacks of TNT from your gathering talent before the walls fall"),
    WALLS3_WOLF_SMASH(AchievementGameType.WALLS3, 10, "Wolf smash", "Get 10 Final Kills with an indirect hit using Lycanthropy."),
    WALLS3_GONE_VEGAN(AchievementGameType.WALLS3, 10, "Gone vegan", "Survive a whole game as Zombie, while eating nothing but bread, and win."),
    WALLS3_GRAVE_ROBBER(AchievementGameType.WALLS3, 10, "Grave robber", "Have the treasure looter ability activate 1000 times as Pirate"),
    WALLS3_THROWING_COCONUTS(AchievementGameType.WALLS3, 10, "Throwing hot coconuts", "Get 9 Final Kills with Fireballs as Blaze in one game"),
    WALLS3_BIRDS_EYE(AchievementGameType.WALLS3, 10, "Bird's Eye", "Hit an enemy with Shadow Burst from over 50 blocks away."),
    WALLS3_TREASURE_HUNTER(AchievementGameType.WALLS3, 10, "Treasure hunter", "Find 300 Golden Apples total from your gathering skill as Hunter"),
    WALLS3_LEGENDARY_SQUID(AchievementGameType.WALLS3, 15, "Legendary Squid", "Get 20 FK's or FA's in a single game as Squid"),
    WALLS3_LEGENDARY_HUNTER(AchievementGameType.WALLS3, 15, "Legendary Hunter", "Get 20 FK's or FA's in a single game as Hunter"),
    WALLS3_SAVE_YOUR_STUFF(AchievementGameType.WALLS3, 5, "Save your stuff", "Buy an Enderchest"),
    WALLS3_ALOTV1(AchievementGameType.WALLS3, 10, "ALOTv1", "Kill a wither as Zombie while being the last player alive on your team."),
    WALLS3_I_FEEL_SICK(AchievementGameType.WALLS3, 10, "I feel sick", "Gather from your mining ability and consume 8 absorption potions in one game as Squid"),
    WALLS3_FIRST_SKILL_UPGRADE(AchievementGameType.WALLS3, 5, "Going to the Gym", "Unlock your first Skill upgrade"),
    WALLS3_COMING_THROUGH(AchievementGameType.WALLS3, 10, "Coming through!", "Hit 5 enemies while charging forward in deathmatch as Moleman"),
    WALLS3_MOODSETTER(AchievementGameType.WALLS3, 10, "Moodsetter", "Craft your own jukebox and play a tune."),
    WALLS3_BLAZE_PARTY(AchievementGameType.WALLS3, 10, "Blaze party", "Have 6 Blazes active at once during deathmatch as Blaze"),
    WALLS3_REMOTE_DETONATION(AchievementGameType.WALLS3, 10, "Remote detonation", "Get 5 total final kills with your Minion as Creeper"),
    WALLS3_TIME_TO_DIET(AchievementGameType.WALLS3, 10, "Time to diet", "Eat 10,000 Steaks as Werewolf"),
    WALLS3_TO_INFINITY(AchievementGameType.WALLS3, 10, "To Infinity", "Activate Tempest 5 times in a row, without losing Speed III"),
    WALLS3_LEGENDARY_PIRATE(AchievementGameType.WALLS3, 15, "Legendary Pirate", "Get 20 FK's or FA's in a single game as Pirate"),
    WALLS3_HUNTING_SEASON(AchievementGameType.WALLS3, 10, "Hunting season", "Travel 100,000 blocks with Speed as Werewolf"),
    WALLS3_CIRCLE_OF_TRUST(AchievementGameType.WALLS3, 10, "Circle of trust", "Damage 10 people at once with one Pigman bubble"),
    WALLS3_LEGENDARY_SKELETON(AchievementGameType.WALLS3, 15, "Legendary Skeleton", "Get 20 FK's or FA's as Skeleton in a single game"),
    WALLS3_SNEAK_ATTACK(AchievementGameType.WALLS3, 10, "Sneak attack", "Get 200 total final kills from behind as Enderman"),
    WALLS3_BLOOD_LUST(AchievementGameType.WALLS3, 5, "Blood Lust", "Deal 700 damage to withers in one game"),
    WALLS3_LEGENDARY_SPIDER(AchievementGameType.WALLS3, 15, "Legendary Spider", "Get 20 FK's or FA's in a single game as Spider"),
    WALLS3_LEGENDARY_WEREWOLF(AchievementGameType.WALLS3, 15, "Legendary Werewolf", "Get 20 FK's or FA's in a single game as Werewolf"),
    WALLS3_SLEEPYTIME(AchievementGameType.WALLS3, 10, "Sleepytime", "Craft and place a bed in 100 games as Zombie"),
    WALLS3_LEGENDARY_ENDERMAN(AchievementGameType.WALLS3, 15, "Legendary Enderman", "Get 20 FK's or FA's in a single game as Enderman"),
    WALLS3_LEGENDARY_PHOENIX(AchievementGameType.WALLS3, 15, "Legendary Phoenix", "Get 20 FK's or FA's in a single game as Phoenix"),
    WALLS3_MUCH_DOGS(AchievementGameType.WALLS3, 10, "Much dogs", "Spawn 5,000 wolves as Shaman"),
    WALLS3_ESC(AchievementGameType.WALLS3, 10, "ESC", "Have sea legs activate 10 times during deathmatch in a single game as Pirate"),
    WALLS3_MARKSMAN(AchievementGameType.WALLS3, 10, "Marksman", "Get 40 FK's from over 50 blocks as Skeleton"),
    WALLS3_LASER_PRECISION(AchievementGameType.WALLS3, 10, "Laser Precision", "Damage ten different players with ten consecutive arcane beams without dying as Arcanist"),
    WALLS3_HAMMER_DOWN(AchievementGameType.WALLS3, 10, "Hammer down", "Damage 6 different players with one Iron Punch as Golem"),
    WALLS3_COLLECTOR(AchievementGameType.WALLS3, 10, "Collector", "Gather 1500 total armor pieces as Pigman"),
    WALLS3_SURPRISE(AchievementGameType.WALLS3, 10, "Surprise!", "Teleport to 5000 total players as Enderman"),
    WALLS3_POTIONS_OF_DEATH(AchievementGameType.WALLS3, 10, "Potions of Death", "Get 10 Final Kills with Arcane Explosion as Arcanist"),
    WALLS3_LEGENDARY_ZOMBIE(AchievementGameType.WALLS3, 15, "Legendary Zombie", "Get 20 FK's or FA's as Zombie in a single game"),
    WALLS3_LEGENDARY_CREEPER(AchievementGameType.WALLS3, 15, "Legendary Creeper", "Get 20 FK's or FA's in a single game as Creeper"),
    WALLS3_HARD_AS_STEEL(AchievementGameType.WALLS3, 10, "Hard as Steel", "Collect 5,000 iron ore with your Arcane beam as Arcanist"),
    WALLS3_MINE_DIAMOND(AchievementGameType.WALLS3, 10, "Front Line", "Mine Diamond Ore"),
    WALLS3_PEACEKREEPER(AchievementGameType.WALLS3, 10, "Peacekreeper", "Win and survive a whole game as Creeper, without ever using your detonate ability"),
    WALLS3_TRUST_ME_IM_A_DOCTOR(AchievementGameType.WALLS3, 10, "Trust me I'm a doctor", "Heal 25,000 total HP as Squid"),
    WALLS3_ON_POINT(AchievementGameType.WALLS3, 10, "On Point", "Land twelve successful arrow hits in a row on twelve different enemies as Hunter"),
    WALLS3_MULTI_KILL(AchievementGameType.WALLS3, 10, "Multi-kill!", "Get 5 Final kills in a period of 7 seconds as Herobrine"),
    WALLS3_YEEHAW(AchievementGameType.WALLS3, 10, "Yeehaw!", "Kill a wither while riding a pig as Hunter"),
    WALLS3_LEGENDARY_HEROBRINE(AchievementGameType.WALLS3, 15, "Legendary Herobrine", "Get 20 FK's or FA's in a single game as Herobrine"),
    WALLS3_THIS_IS_MY_FINAL_FORM(AchievementGameType.WALLS3, 10, "This is my final form!", "Purchase a prestige upgrade for a class"),
    WALLS3_LEGENDARY_DREADLORD(AchievementGameType.WALLS3, 15, "Legendary Dreadlord", "Get 20 FK's or FA's in a single game as Dreadlord"),
    WALLS3_BA_BOOM(AchievementGameType.WALLS3, 10, "BA-BOOM!", "Get 10 FK's with Animal Companion as Hunter"),
    WALLS3_SPEED_RUN(AchievementGameType.WALLS3, 10, "Speedrun", "Attack all three enemy withers within 2 minutes after the walls have fallen as Enderman"),
    WALLS3_FIRST_GATHERING_SKILL_UPGRADE(AchievementGameType.WALLS3, 5, "The Gatherer", "Unlock your first Gathering Skill upgrade"),
    WALLS3_ATTACK_WITHER(AchievementGameType.WALLS3, 5, "Strategic Mind", "Attack an enemy's Wither"),
    WALLS3_LEGENDARY_MOLEMAN(AchievementGameType.WALLS3, 15, "Legendary Moleman", "Get 20 FK's or FA's in a single game as Moleman"),
    WALLS3_YOU_SHALL_NOT_PASS(AchievementGameType.WALLS3, 10, "You shall not pass!", "Get 15 total defensive FK's or FA's as Squid"),
    WALLS3_MAX_SKILLS(AchievementGameType.WALLS3, 10, "This Is Not Even My Final Form", "Max out all skills for one class"),
    WALLS3_VETERAN(AchievementGameType.WALLS3, 15, "Veteran", "Unlock 7 Hero Classes"),
    WALLS3_ITS_ALL_OGRE_NOW(AchievementGameType.WALLS3, 10, "It's all Ogre now!", "As golem, kill the last Wither in the game and win within 12 minutes"),
    WALLS3_FIRE_IN_THE_HOLE(AchievementGameType.WALLS3, 10, "Fire in the hole", "Hit an enemy with your cannonball from over 50 blocks away Pirate"),
    WALLS3_SKELETONS_BEST_FRIEND(AchievementGameType.WALLS3, 10, "Skeleton's best friend", "Mine 100 diamond ore as Skeleton"),
    WALLS3_DEATH_FROM_ABOVE(AchievementGameType.WALLS3, 10, "Death from above", "Get 25 total FK's with Parrots as Pirate"),
    WALLS3_FEELS_BAD(AchievementGameType.WALLS3, 10, "Feels bad...?", "Final kill an enemy by dropshocking to your own death"),
    WALLS3_SPEEDY_MINEMAN(AchievementGameType.WALLS3, 10, "Speedy mineman", "Have shortcut activated for 5 minutes non-stop during deathmatch"),
    WALLS3_COMPETITIVE(AchievementGameType.WALLS3, 10, "Competitive", "Get top final kills at the end of the match"),
    WALLS3_LUCKY_SUNNY(AchievementGameType.WALLS3, 10, "Lucky Sunny", "Find 1000 chests while playing Herobrine"),
    WALLS3_ASHES_TO_BASHES(AchievementGameType.WALLS3, 10, "Ashes to bashes", "Win a game as Phoenix with yourself and at least four teammates, who you've resurrected, still alive"),
    WALLS3_HUG_ME(AchievementGameType.WALLS3, 10, "Hug me", "Heal at least 240 hearts to your teammates as Zombie in a single game."),
    WALLS3_SEASONS_GREETINGS(AchievementGameType.WALLS3, 10, "Seasons Greetings", "Give away 10000 pieces of iron armor to your team during the month of December"),
    WALLS3_GERONIMO(AchievementGameType.WALLS3, 10, "Geronimo!", "Fall a total of 25000 blocks as Spider"),
    WALLS3_BOW_DOWN(AchievementGameType.WALLS3, 10, "Bow down", "Get 7 melee FK's as Skeleton in a single game"),
    WALLS3_MAXIMUM_EFFORT(AchievementGameType.WALLS3, 10, "Maximum Effort", "Get 5 Final Kills in 7 seconds as Dreadlord"),
    WALLS3_REVENGE_OF_THE_WOLVES(AchievementGameType.WALLS3, 10, "Revenge of the Wolves", "Get 30 FK's with your wolves as Shaman."),
    WALLS3_RUSHLORD(AchievementGameType.WALLS3, 10, "Rushlord", "Deal 100,000 wither damage total as Dreadlord"),
    WALLS3_HIGH_ON_ORES(AchievementGameType.WALLS3, 10, "High on ores", "Heal 10000 HP from mining iron ore as Blaze"),
    WALLS3_FIND_CHEST(AchievementGameType.WALLS3, 5, "Chest Finder", "Find a chest while mining"),
    WALLS3_WHIRLWIND(AchievementGameType.WALLS3, 10, "Whirlwind", "Damage 6 players with one tornado as Shaman"),
    WALLS3_NIGHTS_REST(AchievementGameType.WALLS3, 10, "Night's rest", "Heal teammates for 1500 total HP using inferno as Phoenix"),
    WALLS3_WIN_BEFORE_DEATHMATCH(AchievementGameType.WALLS3, 15, "Easy Mode", "Win before the Deathmatch, without dying"),
    WALLS3_BREADLORD(AchievementGameType.WALLS3, 10, "Breadlord", "Craft 2,500 bread as Dreadlord"),
    WALLS3_WHIRLPOOL(AchievementGameType.WALLS3, 10, "Whirlpool", "Damage 5 different players with one Splash as Squid"),
    WALLS3_LEGENDARY_BLAZE(AchievementGameType.WALLS3, 15, "Legendary Blaze", "Get 20 FK's or FA's in a single game as Blaze"),
    WALLS3_THUNDER(AchievementGameType.WALLS3, 10, "Thunder", "Get 2 Final kills with one wrath while playing Herobrine"),
    WALLS3_CRUISING_FLAMES(AchievementGameType.WALLS3, 10, "Cruising flames", "Have one Cleansing Flame arrow's Fireball hit 8 teammates as Phoenix"),
    WALLS3_WIN_WITH_LIVING_WITHER(AchievementGameType.WALLS3, 15, "The Blood of My Enemies", "Win with your Wither still alive"),
    WALLS3_LEGENDARY_SHAMAN(AchievementGameType.WALLS3, 15, "Legendary Shaman", "Get 20 FK's or FA's in a single game as Shaman"),
    WALLS3_TIMBER(AchievementGameType.WALLS3, 10, "Timber!", "Chop 20,000 pieces of wood as Golem"),
    WALLS3_AT_LEAST_HE_TRIED(AchievementGameType.WALLS3, 10, "At least he tried", "Get a defensive final kill"),
    WALLS3_GOTCHA(AchievementGameType.WALLS3, 10, "Gotcha!", "Final kill 2 enemies with one ability use as Moleman"),
    WALLS3_MAX_RENDER_DISTANCE(AchievementGameType.WALLS3, 10, "Max render distance", "Land a fire arrow from 100 blocks away as Blaze"),
    WALLS3_NINJA_7S(AchievementGameType.WALLS3, 10, "Ninja 7s", "Craft an iron sword and get 7 final kills with that sword without dying as Spider"),
    WALLS3_LEGENDARY_GOLEM(AchievementGameType.WALLS3, 15, "Legendary Golem", "Get 20 FK's or FA's in a single game as Golem"),
    WALLS3_BLOWING_BUBBLES(AchievementGameType.WALLS3, 10, "Blowing bubbles", "Activate 6 Pigman bubbles within 25 seconds"),
    WALLS3_MASTERPIECE(AchievementGameType.WALLS3, 10, "Masterpiece", "Kill an enemy wither with a painting as Pigman"),
    WALLS3_MAX_ZOMBIE_SKILLS(AchievementGameType.WALLS3, 10, "Zombie Leader", "Max out all Zombie skills"),
    WALLS3_LEGENDARY_ARCANIST(AchievementGameType.WALLS3, 15, "Legendary Arcanist", "Get 20 FK's or FA's in a single game as Arcanist"),
    WALLS3_STAYIN_ALIVE(AchievementGameType.WALLS3, 10, "Stayin' Alive", "Win a game without dying and get THE final kill with a Jukebox as Shaman"),
    WALLS3_NOT_A_GOLEM(AchievementGameType.WALLS3, 10, "Not a Golem", "Win a game as Herobrine wearing a Diamond Chestplate and Diamond Boots"),
    WALLS3_MASS_DESTRUCTION(AchievementGameType.WALLS3, 10, "Mass destruction", "Break 15,000 blocks with detonate as Creeper"),
    WALLS3_LEGENDARY_PIGMAN(AchievementGameType.WALLS3, 15, "Legendary Pigman", "Get 20 FK's or FA's in a single game as Pigman"),
    WALLS3_CONSTRUCTOR(AchievementGameType.WALLS3, 10, "Constructor", "Place 25,000 total blocks in preparation time as Moleman"),
    WALLS3_MAX_SKELETON_SKILLS(AchievementGameType.WALLS3, 10, "Skeleton Supremacy", "Max out all Skeleton skills"),
    WALLS3_MARTYRDOM(AchievementGameType.WALLS3, 10, "Martyrdom", "Get 10 total FK's with your nest spiders as Spider"),
    WALLS3_TAKING_THE_HEAT(AchievementGameType.WALLS3, 10, "Taking the heat", "Kill an enemy wither while on fire as Golem"),
    WALLS3_ADVANCED_STRATEGIES(AchievementGameType.WALLS3, 5, "Advanced Strategies", "Win a game of Faceoff without your wither dying"),
    WALLS3_UNTOUCHABLE(AchievementGameType.WALLS3, 10, "Untouchable", "Melee 7 different enemies consecutively without taking damage as Enderman"),
    WALLS3_TIME_TO_FEAST(AchievementGameType.WALLS3, 10, "Time to feast", "Harvest 50 Steaks from killing players in a single game."),
    WALLS3_MAX_HEROBRINE_SKILLS(AchievementGameType.WALLS3, 10, "Herobrine Super Saiyan", "Max out all Herobrine skills"),
    COPSANDCRIMS_IS_IT_GOOD_NOW(AchievementGameType.COPSANDCRIMS, 20, "Is it good now?", "Acquire all upgrades on a gun"),
    COPSANDCRIMS_ONE_SHOT_ONE_KIL(AchievementGameType.COPSANDCRIMS, 10, "One shot, one kill", "Get a kill with your first bullet"),
    COPSANDCRIMS_RUN_AWAY(AchievementGameType.COPSANDCRIMS, 5, "RUN AWAY!!", "Plant a bomb"),
    COPSANDCRIMS_CHALLENGE_COMPLETED(AchievementGameType.COPSANDCRIMS, 5, "Challenge Completed!", "Complete a challenge in TDM"),
    COPSANDCRIMS_LIKE_MY_GUN(AchievementGameType.COPSANDCRIMS, 5, "Like my gun?", "Use a reskined gun"),
    COPSANDCRIMS_STREET_ARTIST(AchievementGameType.COPSANDCRIMS, 5, "Street Artist", "Buy all Radio Commands/ Sprays"),
    COPSANDCRIMS_FANCY_NEW_TOYS(AchievementGameType.COPSANDCRIMS, 5, "Fancy New Toys", "Unlock 10 Gun Variations"),
    COPSANDCRIMS_NEVER_TOO_LATE(AchievementGameType.COPSANDCRIMS, 10, "It's never too late", "Win or tie a game being down 0-3"),
    COPSANDCRIMS_UNSTOPPABLE(AchievementGameType.COPSANDCRIMS, 10, "Unstoppable", "Get 15 kills without dying"),
    COPSANDCRIMS_UMADBRO(AchievementGameType.COPSANDCRIMS, 5, "umadbro?", "Use a Taunt"),
    COPSANDCRIMS_DARUDE_SANDSTORM(AchievementGameType.COPSANDCRIMS, 5, "Darude Sandstorm", "Win on both Sandstorm and Alleyway"),
    COPSANDCRIMS_GUN_MASTER(AchievementGameType.COPSANDCRIMS, 10, "Gun Master", "Get a kill with 5 different weapons in a game of Defusal"),
    COPSANDCRIMS_SAMURAI_WARRIOR(AchievementGameType.COPSANDCRIMS, 5, "Samurai Warrior", "Get a knife kill"),
    COPSANDCRIMS_SECRET_ORDER(AchievementGameType.COPSANDCRIMS, 5, "Secret Order", "Win a Challenge Mode game"),
    COPSANDCRIMS_TEAM_COMMUNICATOR(AchievementGameType.COPSANDCRIMS, 5, "Team Communicator", "Unlock 20 Radio Commands"),
    COPSANDCRIMS_WHERES_MY_NUKE(AchievementGameType.COPSANDCRIMS, 15, "Where's my Nuke?", "Get 25 kills without dying"),
    COPSANDCRIMS_HOMING_BULLETS(AchievementGameType.COPSANDCRIMS, 10, "Homing Bullets", "Get 7 kills in one round"),
    COPSANDCRIMS_TOO_EASY(AchievementGameType.COPSANDCRIMS, 5, "Too Easy", "Defuse a bomb with the Defuser Kit 9000"),
    COPSANDCRIMS_PENTAAAA(AchievementGameType.COPSANDCRIMS, 15, "PENTAAAA!!!", "Get 5 kills in less than 7 seconds"),
    COPSANDCRIMS_HUNTING_SEASON(AchievementGameType.COPSANDCRIMS, 5, "It's hunting season", "Buy a 50cal in round 2"),
    COPSANDCRIMS_THE_CARRIER(AchievementGameType.COPSANDCRIMS, 10, "The Carrier", "Win a game with at least 1 bomb planted, 1 defused and 10 kills"),
    COPSANDCRIMS_CLOSE_CALL(AchievementGameType.COPSANDCRIMS, 10, "Close Call", "Defuse a bomb with less than 3 seconds before detonation"),
    COPSANDCRIMS_GRAFITTI_KING(AchievementGameType.COPSANDCRIMS, 5, "Grafitti King", "Use a Spray"),
    COPSANDCRIMS_ON_FIRE(AchievementGameType.COPSANDCRIMS, 10, "I'm on FIRE!", "Obtain a kill streak of 10 in TDM"),
    COPSANDCRIMS_GRENADE_KILL(AchievementGameType.COPSANDCRIMS, 5, "BOOM!", "Get a grenade kill"),
    COPSANDCRIMS_DEATHMATCH_SPECIALIST(AchievementGameType.COPSANDCRIMS, 10, "TDM Specialist", "Obtain at least 300 points in TDM"),
    COPSANDCRIMS_FRIENDLY_GAME(AchievementGameType.COPSANDCRIMS, 5, "Less Talky Talky, more Pew Pew", "Play a game of Challenge Mode"),
    COPSANDCRIMS_SNEAKY(AchievementGameType.COPSANDCRIMS, 5, "Sneaky!", "Defuse a bomb with enemies left alive"),
    COPSANDCRIMS_COMEBACK_STORY(AchievementGameType.COPSANDCRIMS, 5, "Comeback Story", "Be the last man alive and win in a round of Defusal"),
    COPSANDCRIMS_TRIIPPLEE(AchievementGameType.COPSANDCRIMS, 10, "TRIIPPLEE!!!", "Get 3 kills in less than 3 seconds"),
    COPSANDCRIMS_WARFARE_STYLIST(AchievementGameType.COPSANDCRIMS, 5, "Warfare Stylist", "Unlock 4 Armor Variations"),
    COPSANDCRIMS_FLAWLESS(AchievementGameType.COPSANDCRIMS, 10, "Flawless", "Win a game without losing a single round"),
    SPEEDUHC_POTION_BREWER(AchievementGameType.SPEEDUHC, 5, "This Better Work", "Brew a Potion"),
    SPEEDUHC_RIDE_PIG(AchievementGameType.SPEEDUHC, 5, "Oink", "Ride a Pig"),
    SPEEDUHC_USE_ENDERPEARL(AchievementGameType.SPEEDUHC, 5, "Ninja!", "Use an Ender Pearl"),
    SPEEDUHC_GOLDEN_APPLE(AchievementGameType.SPEEDUHC, 5, "Newton's Laws", "Find a Golden Apple from a tree"),
    SPEEDUHC_NATURAL_TALENT(AchievementGameType.SPEEDUHC, 10, "Natural Talent", "Obtain 100 kills with 7 different Masteries"),
    SPEEDUHC_MASTERY_UNLOCK(AchievementGameType.SPEEDUHC, 10, "New Strategies", "Find a Mastery in the Tear Exchange"),
    SPEEDUHC_ENCHANTED_ARMOR(AchievementGameType.SPEEDUHC, 5, "Ready for the Fashion Week", "Wear a fully enchanted set of Armor"),
    SPEEDUHC_SKELETON_BOW(AchievementGameType.SPEEDUHC, 5, "Generous Pile of Bones", "Obtain an enchanted Bow from a Skeleton"),
    SPEEDUHC_SNIPE_PLAYER(AchievementGameType.SPEEDUHC, 10, "Executed!", "Kill a player at least 75 blocks away with a bow"),
    SPEEDUHC_KIT_SPECIALIST(AchievementGameType.SPEEDUHC, 10, "Kit Specialist", "Unlock 15 different Kits"),
    SPEEDUHC_KIT_UNLOCK(AchievementGameType.SPEEDUHC, 5, "Feels Good Man", "Unlock a Kit using Salt"),
    SPEEDUHC_KILL_TNT(AchievementGameType.SPEEDUHC, 10, "I Do Things My Way", "Kill a player using TNT"),
    SPEEDUHC_MELON_SMASHER(AchievementGameType.SPEEDUHC, 5, "One Melon a Day Keeps the Doctor Away", "Smash a Melon"),
    SPEEDUHC_GOD_APPLE(AchievementGameType.SPEEDUHC, 5, "Stay Golden", "Eat a God Apple"),
    SPEEDUHC_PAPER_CUT(AchievementGameType.SPEEDUHC, 10, "Paper Cut", "Kill a player with a Map"),
    SPEEDUHC_ENCHANTED_BOOK(AchievementGameType.SPEEDUHC, 5, "Knowledge!", "Obtain an Enchanted Book from killing a player in Insane Mode"),
    SPEEDUHC_RUSHER(AchievementGameType.SPEEDUHC, 5, "One Happy Rusher", "Get a kill within 30 seconds of the game starting"),
    SPEEDUHC_DOMINATION(AchievementGameType.SPEEDUHC, 5, "Domination Achieved", "Win a Team game with your team having at least 10 kills"),
    SPEEDUHC_KILL_GHAST(AchievementGameType.SPEEDUHC, 5, "Tears for Fears", "Kill a Ghast"),
    GENERAL_VIP(AchievementGameType.GENERAL, 10, "Very Important Person", "Become a VIP"),
    GENERAL_FRIENDS_25(AchievementGameType.GENERAL, 10, "Popular", "Get 25+ friends"),
    GENERAL_YOUTUBER(AchievementGameType.GENERAL, 10, "EEEEKK!", "Be in the same lobby as a YouTuber"),
    GENERAL_FIRST_JOIN(AchievementGameType.GENERAL, 5, "Achievement Get! Hypixel Server!", "Join the Hypixel Network for the first time"),
    GENERAL_USE_PORTAL(AchievementGameType.GENERAL, 5, "Thinking with Portals", "Use a portal to teleport to a game"),
    GENERAL_FIRST_GAME(AchievementGameType.GENERAL, 5, "Baby Steps", "Play a minigame"),
    GENERAL_FIRST_CHAT(AchievementGameType.GENERAL, 5, "Let the world hear your voice!", "Use chat for the first time"),
    GENERAL_FIRST_FRIEND(AchievementGameType.GENERAL, 5, "Not forever alone...", "Make a friend using the friendsystem"),
    GENERAL_ACHIEVEMENT_NPC(AchievementGameType.GENERAL, 5, "Achievements!?!", "Click the Achievements Guide in the Main Lobby"),
    GENERAL_VIP_PLUS(AchievementGameType.GENERAL, 15, "Very Very Important Person", "Become a VIP+"),
    GENERAL_CREEPERBOOK(AchievementGameType.GENERAL, 5, "Creeperbook", "Link your Minecraft account withyour forum account"),
    GENERAL_GIFTING(AchievementGameType.GENERAL, 15, "Gift Giver", "Send a gift bundle to oneof your friends"),
    GENERAL_FIRST_PARTY(AchievementGameType.GENERAL, 10, "Strength in numbers", "Party up for the first time"),
    GENERAL_A_LONG_JOURNEY_BEGINS(AchievementGameType.GENERAL, 5, "A long journey begins", "Complete a quest"),
    UHC_CRAFTING_REVOLUTION(AchievementGameType.UHC, 5, "Crafting revolution", "Use a custom recipe in game"),
    UHC_FEARED_HUNTERS(AchievementGameType.UHC, 10, "Feared Hunters", "Win a game before Deathmatch"),
    UHC_PUPPY(AchievementGameType.UHC, 5, "Oh Daddy pleaaase, I want a puppy!!", "Tame a wolf"),
    UHC_RIDE_A_HORSE(AchievementGameType.UHC, 5, "Epic music please?", "Ride a Horse"),
    UHC_KIT_MASTERY(AchievementGameType.UHC, 5, "Kit Mastery", "Unlock the tier 3 of a kit"),
    UHC_BOMBERMAN(AchievementGameType.UHC, 5, "Bomberman", "Kill an Enemy with TNT"),
    UHC_ELDORADO(AchievementGameType.UHC, 10, "Eldorado", "Craft a Notch Apple"),
    UHC_MUSIC(AchievementGameType.UHC, 5, "Make music not war!", "Craft a Jukebox and play a music disk"),
    UHC_ROBIN_HOOD(AchievementGameType.UHC, 15, "Robin Hood", "Kill a player with a bow, over 100 blocks away"),
    UHC_NOTHING_CAN_STOP_US(AchievementGameType.UHC, 15, "Nothing can stop us!", "Kill an enderdragon with your team"),
    UHC_ENDERKIND(AchievementGameType.UHC, 10, "Encounter of the Enderkind", "Kill an Enderman"),
    UHC_DEATHS_SCYTHE(AchievementGameType.UHC, 10, "Death's Scythe", "Craft the Death's Scythe"),
    UHC_DEUX_EX_MACHINA(AchievementGameType.UHC, 10, "Deux Ex Machina", "Craft the Deus Ex Machina"),
    UHC_EXODUS(AchievementGameType.UHC, 10, "Exodus", "Craft the Exodus"),
    UHC_NO_PROBLEM_HERE(AchievementGameType.UHC, 10, "No Problem Here", "Kill an entire team by yourself"),
    UHC_WEALTHY_CHAMPION(AchievementGameType.UHC, 10, "Wealthy Champion", "Max out 7 professions"),
    UHC_ULTIMATE_RECIPE(AchievementGameType.UHC, 10, "This is where the fun begins", "Craft an Ultimate Recipe"),
    UHC_ULTIMATELY_WEALTHY(AchievementGameType.UHC, 10, "Ultimately Wealthy", "Unlock 10 Extra Ultimates"),
    UHC_AXE_OF_PERUN(AchievementGameType.UHC, 5, "Axe of Perun", "Craft the Axe of Perun"),
    UHC_BYE_CRUEL_WORLD(AchievementGameType.UHC, 5, "Bye cruel world!", "Enter the Nether"),
    UHC_CHAMPION_RANK(AchievementGameType.UHC, 15, "Champion!", "Get the Champion Rank"),
    UHC_PRESTIGIOUS(AchievementGameType.UHC, 5, "Prestigious!", "Prestige a Profession"),
    UHC_ULTIMATE_CRAFTING(AchievementGameType.UHC, 10, "This is only the first one", "Unlock an Ultimate Crafting"),
    UHC_GHAST(AchievementGameType.UHC, 10, "A good Ghast is a dead Ghast", "Kill a Ghast"),
    UHC_SEAFOOD(AchievementGameType.UHC, 5, "I only like seafood", "Obtain a fish from fishing"),
    UHC_SHINY_ROCK(AchievementGameType.UHC, 5, "Lovely shiny rock", "Mine a diamond"),
    UHC_DRINK_WITH_CAUTION(AchievementGameType.UHC, 5, "Drink with caution", "Drink a potion"),
    UHC_GHOST_RIDER(AchievementGameType.UHC, 10, "Ghost Rider", "Craft the Daredevil"),
    UHC_TABLETS_OF_DESTINY(AchievementGameType.UHC, 10, "Tablets of Destiny", "Craft the Tablets of Destiny"),
    UHC_TOTAL_DOMINATION(AchievementGameType.UHC, 5, "Total domination", "Be the player with the most kills at the end of the game"),
    UHC_RAMPAGE(AchievementGameType.UHC, 10, "Rampage", "Kill 10 players in a single game"),
    UHC_CHEST_OF_FATE(AchievementGameType.UHC, 10, "Chest of Fate", "Craft the Chest of Fate"),
    UHC_DICE_OF_GOD(AchievementGameType.UHC, 10, "Dice of God", "Craft the Dice of God"),
    UHC_ADRENALINE(AchievementGameType.UHC, 5, "Adrenaline", "Eat a player head"),
    BLITZ_FIRST_BLOOD(AchievementGameType.BLITZ, 10, "First Blood", "Get the first kill in a game"),
    BLITZ_FIND_BLITZ(AchievementGameType.BLITZ, 10, "So powerful...", "Find a Blitz Star"),
    BLITZ_USE_WOLF_TAMER(AchievementGameType.BLITZ, 5, "Raised by Wolves", "Use the WolfTamer kit"),
    BLITZ_TITANIUM(AchievementGameType.BLITZ, 15, "Titanium", "Wear a full set of Diamond Armor"),
    BLITZ_RAMPAGE(AchievementGameType.BLITZ, 10, "Rampage", "Get 10 kills in a one game"),
    BLITZ_WIN_BEFORE_DEATHMATCH(AchievementGameType.BLITZ, 10, "Immortal", "Win before the deathmatch"),
    BLITZ_FIRST_GAME(AchievementGameType.BLITZ, 5, "It all begins here", "Play Blitz for the first time"),
    BLITZ_LUCKY_MINIONS(AchievementGameType.BLITZ, 5, "Lucky minions", "Spawn 13 mobs in a game"),
    BLITZ_RABBITS_FOOT(AchievementGameType.BLITZ, 5, "Rabbit's Foot", "Survive a fall of at least 50 blocks"),
    BLITZ_FULL_INVENTORY(AchievementGameType.BLITZ, 5, "Hoarder", "Fill up your inventory"),
    BLITZ_KILL_WITHOUT_KIT(AchievementGameType.BLITZ, 10, "Speed Kills", "Kill two people before you get your kit"),
    BLITZ_FINALLY(AchievementGameType.BLITZ, 15, "Finally", "Get a kit to level X"),
    BLITZ_APOCALYPSE(AchievementGameType.BLITZ, 10, "BURN THEM ALL!", "Use Apocalypse Blitz"),
    BLITZ_NOT_SKYWARS(AchievementGameType.BLITZ, 5, "This is not Skywars", "Throw a player into the void"),
    BLITZ_UNFORTUNATE(AchievementGameType.BLITZ, 5, "Unfortunate", "Get killed by your own roulette"),
    BLITZ_BLITZ_MANIAC(AchievementGameType.BLITZ, 5, "Blitz Maniac", "Purchase 10 Blitz Stars"),
    BLITZ_YOUTUBER(AchievementGameType.BLITZ, 10, "Play with the YouTuber", "Play a game with a YouTuber"),
    BLITZ_ENCHANT_SWORD(AchievementGameType.BLITZ, 10, "Ooh...Magic!", "Enchant a sword"),
    BLITZ_ENCHANTED_ARMOR(AchievementGameType.BLITZ, 10, "Shieldwall", "Wear a fully enchanted armor set"),
    BLITZ_GET_DIAMOND_SWORD(AchievementGameType.BLITZ, 10, "My Precious", "Obtain a Diamond Sword"),
    BLITZ_SPAWN_HORSE(AchievementGameType.BLITZ, 10, "HORSEEEYYY", "Spawn a horse"),
    BLITZ_CHAMPION(AchievementGameType.BLITZ, 5, "Champion", "Kill a player that is using a level X Kit"),
    BLITZ_UNSTOPPABLE(AchievementGameType.BLITZ, 10, "Unstoppable", "Kill 5 players within 10 seconds"),
    BLITZ_INVINCIBLE(AchievementGameType.BLITZ, 15, "Invincible", "Win a game without taking any damage"),
    BLITZ_NO_PROBLEM(AchievementGameType.BLITZ, 5, "No Problem", "Win a game without killing anyone"),
    BLITZ_AFTERBURNER(AchievementGameType.BLITZ, 5, "Afterburner", "Kill a player with Fire"),
    BLITZ_FIND_HEAD(AchievementGameType.BLITZ, 10, "ADMIN ABOOSE", "Find codename_B or hypixel's head"),
    BLITZ_SEVEN_KITS(AchievementGameType.BLITZ, 15, "Can't Decide!", "Purchase one level of at least 7 kits"),
    BLITZ_FISH_KILL(AchievementGameType.BLITZ, 10, "Pounded", "Kill someone with the 1 Pound Fish"),
    BLITZ_NO_REGRETS(AchievementGameType.BLITZ, 5, "No regrets", "Craft a Diamond Hoe"),
    BLITZ_COIN_FESTIVAL(AchievementGameType.BLITZ, 5, "Coin Festival", "Find a Coin Chest"),
    BLITZ_COOKING_EXPERT(AchievementGameType.BLITZ, 5, "Cooking Expert", "Craft a Golden Apple"),
    BLITZ_BOMBERMAN(AchievementGameType.BLITZ, 5, "Bomberman", "Kill a player with TNT"),
    BLITZ_NO_LOOTING(AchievementGameType.BLITZ, 10, "IMPOSIBRU", "Win without looting any chests"),
    BLITZ_PIGRIDER(AchievementGameType.BLITZ, 5, "#pigrider77", "Ride a pig during deathmatch"),
    BLITZ_RAMBO(AchievementGameType.BLITZ, 10, "Rambo", "Kill a player using the Rambo kit"),
    BLITZ_LEVEL_SEVEN(AchievementGameType.BLITZ, 15, "Lucky #7", "Get a kit to level 7"),
    BLITZ_CRAFT_BREAD(AchievementGameType.BLITZ, 5, "Peeta Mellark", "Craft bread"),
    BLITZ_UNDER_THE_SEA(AchievementGameType.BLITZ, 5, "Under the sea", "Use a Fishing Rod to catch a Clownfish"),
    WALLS_FIRST_KIT(AchievementGameType.WALLS, 5, "Getting Ready", "Unlock your first starter kit"),
    WALLS_GET_DIAMOND_SWORD(AchievementGameType.WALLS, 10, "Gem + Sticks = Kills", "Obtain a diamond sword"),
    WALLS_CREATE_PORTAL(AchievementGameType.WALLS, 5, "Zombie pigmen EVERYWHERE!?", "Make a Nether Portal in Walls"),
    WALLS_RIDE_HORSE(AchievementGameType.WALLS, 5, "Horse Tamer", "Ride a Horse after the walls fall"),
    WALLS_CRAFT_FLINT(AchievementGameType.WALLS, 5, "Pyromaniac", "Craft Flint and Steel"),
    WALLS_CRAFT_BOAT(AchievementGameType.WALLS, 5, "Castaway", "Craft a boat"),
    WALLS_TEN_KILLS(AchievementGameType.WALLS, 10, "Disaster", "Get ten kills in one game"),
    WALLS_SOLE_SURVIVOR(AchievementGameType.WALLS, 10, "Sole Survivor", "Win a game as the last survivoron your team"),
    WALLS_VAMPIRISM(AchievementGameType.WALLS, 10, "This isn't VampireZ...", "Get the Vampirism perk to level 3"),
    WALLS_NO_TEAM_DEATHS(AchievementGameType.WALLS, 15, "Stick Together", "Win a game with no deaths onyour team"),
    WALLS_FIRST_PERK(AchievementGameType.WALLS, 5, "Getting Stronger", "Unlock your first perk"),
    WALLS_CATCH_FISH(AchievementGameType.WALLS, 5, "Rod God", "Catch a fish"),
    WALLS_KILL_CLIFF(AchievementGameType.WALLS, 10, "This is SPARTA", "Kill a player by hitting them off a cliff"),
    WALLS_BERSERK(AchievementGameType.WALLS, 10, "Conan the Barbarian", "Get the Berserk perk to level 3"),
    WALLS_CANADIAN_KIT(AchievementGameType.WALLS, 5, "Oh Canada!", "Get the Canadian Starter Kit"),
    WALLS_STARTER_KITS(AchievementGameType.WALLS, 15, "MOAR!!", "Unlock 15 Starter Kits"),
    WALLS_ENGINEER(AchievementGameType.WALLS, 5, "Engineer", "Obtain TNT, Pressure Plate,Lava Bucket, and a Piston"),
    WALLS_REVENGE(AchievementGameType.WALLS, 5, "Avenged!", "Kill a player that has killedone of your teammates"),
    BEDWARS_IRON_PUNCH(AchievementGameType.BEDWARS, 5, "Iron Punch", "Get a kill with an Iron Golem"),
    BEDWARS_BUILDER(AchievementGameType.BEDWARS, 5, "Builder", "Place over 200 blocks in a game"),
    BEDWARS_SUPER_LOOTER(AchievementGameType.BEDWARS, 10, "Super looter", "Obtain at least 20 Gold Ingots from enemies in a game"),
    BEDWARS_ALCHEMIST(AchievementGameType.BEDWARS, 5, "Alchemist", "Buy 10 Potions in a game"),
    BEDWARS_STRATEGIST(AchievementGameType.BEDWARS, 10, "Strategist", "Purchase the Reinforced Armor IV team upgrade"),
    BEDWARS_ULTIMATE_DEFENSE(AchievementGameType.BEDWARS, 5, "The Ultimate Defense", "Place 8 Obsidian blocks around your bed"),
    BEDWARS_FIREBALLS(AchievementGameType.BEDWARS, 5, "Great lord of fire!", "Have 10 Fireballs in your inventory at the same time"),
    BEDWARS_SHEAR_LUCK(AchievementGameType.BEDWARS, 5, "Shear Luck", "Kill a player with shears!"),
    BEDWARS_GEARED_UP(AchievementGameType.BEDWARS, 5, "Geared up!", "Purchase the Diamond armor & sword"),
    BEDWARS_SURVIVOR(AchievementGameType.BEDWARS, 10, "Survivor", "Win a game without dying"),
    BEDWARS_DIAMOND_HOARDER(AchievementGameType.BEDWARS, 10, "Diamond Hoarder", "Collect at least 50 Diamonds in a game"),
    BEDWARS_SLAYER(AchievementGameType.BEDWARS, 10, "Dragon Slayer", "Kill an Ender Dragon"),
    BEDWARS_EMERALD_HOARDER(AchievementGameType.BEDWARS, 10, "Emerald Hoarder", "Collect at least 25 Emeralds in a game"),
    BEDWARS_BED_TRAP(AchievementGameType.BEDWARS, 5, "You can't trap me!", "Destroy a bed within 10 seconds of activating the enemy trap"),
    BEDWARS_TEAM_PLAYER(AchievementGameType.BEDWARS, 5, "Team Player", "Place an Emerald in your team chest"),
    BEDWARS_DONT_NEED_BED(AchievementGameType.BEDWARS, 10, "I don't need a bed!", "Survive for 10 minutes without a bed."),
    BEDWARS_ALREADY_OVER(AchievementGameType.BEDWARS, 10, "Already over?", "Win a game within 10 minutes"),
    BEDWARS_MERCILESS(AchievementGameType.BEDWARS, 5, "Merciless", "Final Kill 5 enemies in one game"),
    BEDWARS_GOLEM(AchievementGameType.BEDWARS, 10, "Golem's Rose", "Kill 5 enemy Golems in a single game"),
    BEDWARS_SNIPER(AchievementGameType.BEDWARS, 10, "The Sniper", "Kill a player from at least 40 blocks away"),
    BEDWARS_PICKAXE_CHALLENGE(AchievementGameType.BEDWARS, 5, "Pointless Challenge", "Win a game without killing an enemy with a sword"),
    BEDWARS_FIRST(AchievementGameType.BEDWARS, 5, "Speedy Bridger!", "Be the first player to obtain an Emerald from the middle island"),
    BEDWARS_DESTROY_BEDS(AchievementGameType.BEDWARS, 15, "Getting the job done", "Destroy half of the beds in one game"),
    BEDWARS_FIRST_BLOOD(AchievementGameType.BEDWARS, 5, "First Blood", "Be the first player to kill an enemy"),
    QUAKE_SHOW_ME_THE_MONEY(AchievementGameType.QUAKE, 15, "Show me the money!", "Unlock the Polished Bling Caseor the 1.0s trigger"),
    QUAKE_GOOD_GUY_GAMER(AchievementGameType.QUAKE, 5, "Good Guy Gamer", "Say GG at the end of a game"),
    QUAKE_BAKING_A_DOZEN(AchievementGameType.QUAKE, 5, "Baking a dozen", "Win a game by 12 kills in Quake"),
    QUAKE_BILLY_TALENT(AchievementGameType.QUAKE, 5, "Billy Talent", "Win a game using a custom Railgun"),
    QUAKE_WHAT_HAVE_I_DONE(AchievementGameType.QUAKE, 5, "What have I done...", "Gib a staff member"),
    QUAKE_DOUBLING_UP(AchievementGameType.QUAKE, 5, "Doubling up", "Be the first to 10 kills in Quake"),
    QUAKE_PERFECTIONNIST(AchievementGameType.QUAKE, 5, "Perfectionist", "Do at least 4 killing sprees in 1 game"),
    QUAKE_HUMILIATION(AchievementGameType.QUAKE, 10, "Humiliation", "Kill the same person 4 times in a row"),
    QUAKE_OH_BABY_A_TRIPLE(AchievementGameType.QUAKE, 10, "Oh baby, a triple!", "Get 3 headshot kills with one shot"),
    QUAKE_APPLE_CORER(AchievementGameType.QUAKE, 5, "I only use Apple sorry", "Win a game using the Apple Corer"),
    QUAKE_FROG(AchievementGameType.QUAKE, 10, "Are you a frog?", "Dash 75 times in one game"),
    QUAKE_PERFECTION(AchievementGameType.QUAKE, 5, "Perfection", "Win a game without dying"),
    QUAKE_FANATIC(AchievementGameType.QUAKE, 5, "Fanatic!", "Win a game using the Budder Slapper"),
    QUAKE_ONE_IN_THE_CHAMBER(AchievementGameType.QUAKE, 15, "One in the Chamber", "Win a game using the 9.0s trigger"),
    QUAKE_PLATINUM_PLATED(AchievementGameType.QUAKE, 5, "Platinum plated", "Win a game using the Platinum Smelter"),
    QUAKE_SIMPLE_THINGS(AchievementGameType.QUAKE, 5, "Simple Things", "Win a game using the Basic Railgun"),
    QUAKE_UNTOUCHABLE(AchievementGameType.QUAKE, 10, "Untouchable", "Kill 15 players without dying"),
    QUAKE_RIP(AchievementGameType.QUAKE, 10, "R. I. P.", "Win a game using The Reaper"),
    QUAKE_GOING_UP_IN_LIFE(AchievementGameType.QUAKE, 5, "Going up in life", "Win a game using the Superior Railgun"),
    QUAKE_LOOKING_FANCY(AchievementGameType.QUAKE, 5, "Looking Fancy", "Unlock your first hat"),
    QUAKE_ITS_SO_SHINY(AchievementGameType.QUAKE, 5, "It's soo Shiny!", "Win a game using the Hyper Beam Railgun"),
    QUAKE_FLY(AchievementGameType.QUAKE, 10, "I believe I can fly", "Get a kill while falling down"),
    QUAKE_FIRST_KILL(AchievementGameType.QUAKE, 5, "First kill", "Be the first person to kill someone"),
    QUAKE_GRAB_IT_ALL(AchievementGameType.QUAKE, 5, "Grab it all", "Win a game using The Harvester"),
    QUAKE_TEAM_PLAYER(AchievementGameType.QUAKE, 5, "Team Player", "Win a team game"),
    QUAKE_DARK_SIDE(AchievementGameType.QUAKE, 5, "Joined the dark side", "Win a game using the Gun of Darkness"),
    QUAKE_PRESIDENTIAL(AchievementGameType.QUAKE, 5, "Presidential!", "Win a game using the Bling Bling Thing"),
    QUAKE_NOT_WORKING(AchievementGameType.QUAKE, 5, "Not working", "Punch a player"),
    QUAKE_WAT(AchievementGameType.QUAKE, 5, "wat", "Win a game using Le Bizarre"),
    QUAKE_LOVE_IS_IN_THE_AIR(AchievementGameType.QUAKE, 5, "Love is in the air", "Win a game using the Lovegun"),
    QUAKE_MY_PRECIOUS(AchievementGameType.QUAKE, 5, "My precioussss", "Win a game using the BFG"),
    QUAKE_BOGOF(AchievementGameType.QUAKE, 5, "B.O.G.O.F.", "Get a double kill"),
    QUAKE_INCREDIBLE(AchievementGameType.QUAKE, 10, "Incredible", "Kill 10 players without missing a shot"),
    QUAKE_LOOKIN_GOOD(AchievementGameType.QUAKE, 5, "Lookin' good!", "Win a game using the Fabled Railgun"),
    QUAKE_DIAMONDS_TO_YOU(AchievementGameType.QUAKE, 5, "Diamonds to you!", "Win a game using the Creeper Railgun"),
    QUAKE_CALM_DOWN(AchievementGameType.QUAKE, 5, "Calm down", "Shut down someone while Dominating"),
    QUAKE_BUBBLY(AchievementGameType.QUAKE, 5, "Bubbly, isn't it?", "Win a game using the Blue Lagoon"),
    QUAKE_HEART_STOPPER(AchievementGameType.QUAKE, 10, "Heart Stopper", "Get a triple kill in Quake"),
    QUAKE_HOW_DID_THAT_HAPPEN(AchievementGameType.QUAKE, 15, "How did that happen?", "Win a Solo game with 26 or more kills"),
    QUAKE_ONE_SHOT(AchievementGameType.QUAKE, 5, "You've only got one shot... So make it count", "Get 3 double kills in one game"),
    QUAKE_BUFFING_UP(AchievementGameType.QUAKE, 5, "Buffing Up", "Unlock your first armor set"),
    QUAKE_WANT_A_WARDROBE(AchievementGameType.QUAKE, 5, "Want a wardrobe with that?", "Unlock at least 13 cosmetic items"),
    QUAKE_REDSTONER(AchievementGameType.QUAKE, 5, "Redstoner", "Win a game using the Redstoner"),
    QUAKE_MY_WAY(AchievementGameType.QUAKE, 5, "I did it my way", "Customise your Railgun"),
    QUAKE_IN_MY_WAY(AchievementGameType.QUAKE, 5, "You're in my way!", "Shutdown someone while on akilling streak yourself"),
    TRUECOMBAT_GOLD_FORAGER(AchievementGameType.TRUECOMBAT, 15, "Gold Forager", "Max out a Gold Dust perk"),
    TRUECOMBAT_DOCTOR(AchievementGameType.TRUECOMBAT, 10, "Doctor", "Use more than 20 healing potions in a single game"),
    TRUECOMBAT_NOT_UHC(AchievementGameType.TRUECOMBAT, 5, "This is not UHC!", "Kill a player using Lightning Axe"),
    TRUECOMBAT_KNIGHT(AchievementGameType.TRUECOMBAT, 5, "Knight", "Craft a full set of gold armor"),
    TRUECOMBAT_REDSTONE_DEALER(AchievementGameType.TRUECOMBAT, 5, "Redstone Dealer", "Obtain a stack of Redstone Dust"),
    TRUECOMBAT_GONE_PEACEFUL(AchievementGameType.TRUECOMBAT, 10, "Gone Peaceful", "Win a game without killing anyone"),
    TRUECOMBAT_MULTIKILL(AchievementGameType.TRUECOMBAT, 10, "Multikill", "Get at least 8 kills in a game of Solo Mode"),
    TRUECOMBAT_DIAMOND_ARMOR(AchievementGameType.TRUECOMBAT, 5, "God Amongst Men", "Equip fully enchanted diamond armor"),
    TRUECOMBAT_CROSS_FINGERS(AchievementGameType.TRUECOMBAT, 5, "Cross fingers!", "Activate a Super Lucky Block"),
    TRUECOMBAT_DEADLY_DONATION(AchievementGameType.TRUECOMBAT, 5, "Deadly donation", "Feed the Giant Zombie"),
    TRUECOMBAT_INVINCIBLE(AchievementGameType.TRUECOMBAT, 15, "Invincible", "Win a game without taking any damage"),
    TRUECOMBAT_NOT_TODAY(AchievementGameType.TRUECOMBAT, 5, "Not today!", "Kill a charged creeper"),
    TRUECOMBAT_RAMPAGE(AchievementGameType.TRUECOMBAT, 10, "Rampage", "Get 5 kills in 15 seconds"),
    TRUECOMBAT_LEGENDARY(AchievementGameType.TRUECOMBAT, 10, "Legendary!", "Find a Legendary from the Giant Zombie"),
    TRUECOMBAT_BOOM(AchievementGameType.TRUECOMBAT, 5, "BOOM!", "Kill a player using TNT"),
    TRUECOMBAT_GOLDEN_BOUNTY(AchievementGameType.TRUECOMBAT, 5, "Golden Bounty!", "Find a Golden Skull"),
    TRUECOMBAT_I_FNA(AchievementGameType.TRUECOMBAT, 5, "I FNA!", "Win while wearing a staff member's head"),
    TRUECOMBAT_DOMINATING(AchievementGameType.TRUECOMBAT, 10, "Dominating!", "Kill 2 players before the red walls fall"),
    TRUECOMBAT_MONSTER_HUNTER(AchievementGameType.TRUECOMBAT, 10, "Monster Hunter", "Kill 20 mobs in one game"),
    TRUECOMBAT_STRATEGIST(AchievementGameType.TRUECOMBAT, 5, "Strategist", "Buy an item in the shop in game"),
    TRUECOMBAT_MONSTERKILL(AchievementGameType.TRUECOMBAT, 10, "Monsterkill", "Get at least 15 kills in a game of Team Mode"),
    TRUECOMBAT_DESTINY_CALLS(AchievementGameType.TRUECOMBAT, 5, "Destiny calls!", "Find a Lucky Block"),
    TRUECOMBAT_STICKY_SITUATION(AchievementGameType.TRUECOMBAT, 5, "Sticky Situation", "Get the legendary stick from the weapon lucky block"),
    TRUECOMBAT_TOXIC(AchievementGameType.TRUECOMBAT, 5, "Toxic", "Apply poison to an enemy player"),
    TRUECOMBAT_EXPLOSIVE_ARCHER(AchievementGameType.TRUECOMBAT, 10, "Explosive Archer", "Kill an enemy with the Explosive Bow"),
    TRUECOMBAT_CHANCE(AchievementGameType.TRUECOMBAT, 5, "Chance", "Open every type for lucky block in one game"),
    TRUECOMBAT_ENDER_DRAGON(AchievementGameType.TRUECOMBAT, 5, "Woops", "Spawn an Ender Dragon while activating a Lucky Block"),
    TRUECOMBAT_GOLD_DIGGER(AchievementGameType.TRUECOMBAT, 5, "Gold Digger", "Unlock an item from the Crafting menu using Gold Dust"),
    TRUECOMBAT_DRAGON_SLAYER(AchievementGameType.TRUECOMBAT, 15, "Dragon Slayer", "Kill an Ender Dragon"),
    TRUECOMBAT_MAXED_PERK(AchievementGameType.TRUECOMBAT, 10, "Maxed Perk!", "Max out a tiered perk"),
    TRUECOMBAT_SHARPENED_KATANA(AchievementGameType.TRUECOMBAT, 5, "Sharpened Katana", "Craft a sharpness 5 diamond sword"),
    TRUECOMBAT_THIS_IS_TOO_EASY(AchievementGameType.TRUECOMBAT, 10, "This is too easy!", "Kill at least a player and win the game without using the shop once"),
    TRUECOMBAT_RUSHMODE(AchievementGameType.TRUECOMBAT, 5, "Rush mode ON", "Splash a speed potion on your teammate in Teams Mode"),
    TRUECOMBAT_WHAT_HAVE_I_DONE(AchievementGameType.TRUECOMBAT, 5, "What have I done...", "Have a total of 5 heads in your inventory at the same time"),
    TRUECOMBAT_LIGHTNING_FAST(AchievementGameType.TRUECOMBAT, 10, "Lightning Fast", "Kill a Lucky Villager in Lucky mode"),

    BUILDBATTLE_ARTIST(AchievementGameType.BUILDBATTLE, 15, "Artist", "Use only 1 type of block and have your theme guessed correctly"),
    BUILDBATTLE_BRANIAC(AchievementGameType.BUILDBATTLE, 5, "Braniac", "Be the first player to guess a build correctly"),
    BUILDBATTLE_CLASSIC_MAN(AchievementGameType.BUILDBATTLE, 5, "Classic Man", "Win a game of Build Battle Solo having placed 50 blocks or less"),
    BUILDBATTLE_EVERY_SECOND_COUNTS(AchievementGameType.BUILDBATTLE, 5, "Every Second Counts", "Guess a build correctly in the last 5 seconds"),
    BUILDBATTLE_FANCY(AchievementGameType.BUILDBATTLE, 5, "Fancy", "Buy and equip a hat in the shop"),
    BUILDBATTLE_FAST_TYPER(AchievementGameType.BUILDBATTLE, 10, "Fast Typer", "Be the first player to guess the theme correctly 3 times in a row"),
    BUILDBATTLE_GUESSING_STREAK(AchievementGameType.BUILDBATTLE, 5, "Guessing Streak", "Guess every theme correctly in Guess the Build"),
    BUILDBATTLE_INTUITION(AchievementGameType.BUILDBATTLE, 10, "Intuition", "Be the only player to guess the build correctly"),
    BUILDBATTLE_OVER_99(AchievementGameType.BUILDBATTLE, 10, "It's over 99!", "Get a score of over 99 on Build Battle"),
    BUILDBATTLE_LEGENDARY(AchievementGameType.BUILDBATTLE, 10, "LEGENDARY", "Get a high enough score for Diamond Rain in Build Battle"),
    BUILDBATTLE_MOBSTER(AchievementGameType.BUILDBATTLE, 5, "Mobster", "Spawn a mob"),
    BUILDBATTLE_MUSICIAN(AchievementGameType.BUILDBATTLE, 10, "Musician", "Unlock 25 songs in the shop"),
    BUILDBATTLE_NO_MISTAKES(AchievementGameType.BUILDBATTLE, 10, "No Mistakes", "Have your theme guessed correctly without breaking any blocks"),
    BUILDBATTLE_OBVIOUS(AchievementGameType.BUILDBATTLE, 5, "Obvious", "Build something that everyone guesses correctly"),
    BUILDBATTLE_OOO_SHINY(AchievementGameType.BUILDBATTLE, 5, "Oooo shiny...", "Use Particles on a build in Build Battle"),
    BUILDBATTLE_PERFECT_HARMONY(AchievementGameType.BUILDBATTLE, 10, "Perfect Harmony", "Win a game of Build Battle Teams without breaking a single block you or your teammate placed"),
    BUILDBATTLE_PRO_WINNER(AchievementGameType.BUILDBATTLE, 10, "Pro Winner", "Win a game of Pro Mode"),
    BUILDBATTLE_PROFESSIONAL_BUILDER(AchievementGameType.BUILDBATTLE, 5, "Professional Builder", "Use a pro tool in Pro mode"),
    BUILDBATTLE_STENOGRAPHER(AchievementGameType.BUILDBATTLE, 5, "Stenographer", "Guess the build in less than 10 seconds"),
    BUILDBATTLE_SUPERIOR_VOTE(AchievementGameType.BUILDBATTLE, 5, "Superior Vote", "Use a super vote"),
    BUILDBATTLE_TEAMWORK(AchievementGameType.BUILDBATTLE, 10, "Teamwork", "Win a game of Build Battle Teams"),
    BUILDBATTLE_THAT_WOOD_BE_PERFECT(AchievementGameType.BUILDBATTLE, 10, "That wood Be Perfect", "How much wood can a woodchuck chuck if a woodchuck could chuck wood... aka, win a game by only placing wooden blocks"),
    BUILDBATTLE_HAT_MASTER(AchievementGameType.BUILDBATTLE, 15, "The Hat Master", "Unlock the \"Master Builder Hat\""),



    HALLOWEEN2017_TBR_KRAKEN_ASSAULT_1_25(AchievementGameType.HALLOWEEN2017, 10, "Kraken Assault Great Time", "Complete Kraken Assault in under 01:25"),
    HALLOWEEN2017_SECOND_GHOST(AchievementGameType.HALLOWEEN2017, 5, "Second Ghost", "Find two Ghosts in the Main Lobby"),
    HALLOWEEN2017_TBR_OBSERVATORY_SPIN(AchievementGameType.HALLOWEEN2017, 5, "Observatory Spin Completion", "Complete Observatory Spin in Turbo Bat Racers"),
    HALLOWEEN2017_PUMPKIN_DEATH(AchievementGameType.HALLOWEEN2017, 10, "Pumpkinator Rampage", "Bring 15 pumpkins at once to a Shopkeeper in Bedwars"),
    HALLOWEEN2017_SPOOKY_CHEST(AchievementGameType.HALLOWEEN2017, 5, "Spooky Spooky", "Open 3 Bed Wars Spooky Chests"),
    HALLOWEEN2017_GOOD_TRY(AchievementGameType.HALLOWEEN2017, 5, "Good Try", "Die against the first bomb in Pumpkin Smash"),
    HALLOWEEN2017_TBR_KRAKEN_ASSAULT(AchievementGameType.HALLOWEEN2017, 5, "Kraken Assault Completion", "Complete Kraken Assault in Turbo Bat Racers"),
    HALLOWEEN2017_ALL_GHOSTS(AchievementGameType.HALLOWEEN2017, 15, "All Ghosts", "Find all Ghosts in the Main Lobby"),
    HALLOWEEN2017_TBR_MIDTOWN_TRIP(AchievementGameType.HALLOWEEN2017, 5, "Midtown Trip Completion", "Complete Midtown Trip in Turbo Bat Racers"),
    HALLOWEEN2017_TBR_OBSERVATORY_SPIN_1_10(AchievementGameType.HALLOWEEN2017, 10, "Observatory Spin Great Time", "Complete Observatory Spin in under 01:25"),
    HALLOWEEN2017_HI_THERE(AchievementGameType.HALLOWEEN2017, 5, "Boo!", "Speak to the Halloween Guide in the Main Lobby"),
    HALLOWEEN2017_TBR_MIDTOWN_TRIP_1_20(AchievementGameType.HALLOWEEN2017, 10, "Midtown Trip Great Time", "Complete Midtown Trip in under 01:30"),
    HALLOWEEN2017_PUMPKIN_DANCER(AchievementGameType.HALLOWEEN2017, 10, "Pumpkin Devil", "Obtain 222 points in a single Pumpkin Smash game without dying"),
    CHRISTMAS2017_BOUNCY_CASTLE(AchievementGameType.CHRISTMAS2017, 5, "Bouncy Castle", "Jump on the Bouncy Castle in the Main Lobby"),
    CHRISTMAS2017_EAT_THIS(AchievementGameType.CHRISTMAS2017, 5, "EAT THIS", "Shoot a snowball at another Grinch in Grinch Simulator"),
    CHRISTMAS2017_FEARED_BUT_FAIR(AchievementGameType.CHRISTMAS2017, 10, "Feared but Fair", "Steal a gift from each house in a game of Grinch Simulator"),
    CHRISTMAS2017_GREED_INCARNATE(AchievementGameType.CHRISTMAS2017, 15, "Greed Incarnate", "Steal 42 presents in a single game of Grinch Simulator"),
    CHRISTMAS2017_HAPPY_HOLIDAYS(AchievementGameType.CHRISTMAS2017, 5, "Happy Holidays", "Speak to the Holidays Guide in the Main Lobby"),
    CHRISTMAS2017_LEGENDARY(AchievementGameType.CHRISTMAS2017, 10, "LEGENDARY!", "Find a Legendary Gift in Skywars, Blitz or Murder Mystery"),
    CHRISTMAS2017_NOM_NOM(AchievementGameType.CHRISTMAS2017, 5, "Nom nom", "Craft a Santa Cookie in UHC"),
    CHRISTMAS2017_REAL_SANTA(AchievementGameType.CHRISTMAS2017, 25, "Real Santa", "Find all presents in every lobby"),
    CHRISTMAS2017_RESPECT_YOUR_ELDER(AchievementGameType.CHRISTMAS2017, 5, "Respect Your Elder", "Bring a flower to Grandma in Santa Says"),
    CHRISTMAS2017_SANTA_HELPER(AchievementGameType.CHRISTMAS2017, 5, "Santa Helper", "Bring the right items back to every special character in a single Bed Wars game"),
    CHRISTMAS2017_SEASONAL_QUESTER(AchievementGameType.CHRISTMAS2017, 10, "Seasonal Quester", "Complete 5 Winter Seasonal Quests"),
    CHRISTMAS2017_SHARING_IS_CARING(AchievementGameType.CHRISTMAS2017, 5, "Sharing is Caring", "Give one of your wrapped presents to another player in Bed Wars"),
    CHRISTMAS2017_SUGAR_RUSH(AchievementGameType.CHRISTMAS2017, 5, "Sugar Rush", "Give sugar to a horse in Santa Says"),
    CHRISTMAS2017_THE_HUNT(AchievementGameType.CHRISTMAS2017, 5, "The Hunt Begins", "find two lobby presents"),
    CHRISTMAS2017_UH_UH(AchievementGameType.CHRISTMAS2017, 5, "Uh uh", "When tasked to shoot yourself with an arrow in Santa Says, also shoot someone else"),
    CHRISTMAS2017_ULTIMATE_BLACKSMITH(AchievementGameType.CHRISTMAS2017, 10, "Ultimate Blacksmith", "When given ores in Santa Says, craft a clock"),
    CHRISTMAS2017_WORTH_IT(AchievementGameType.CHRISTMAS2017, 5, "Worth it", "When tasked to kill a chicken in Santa Says, also kill a cow"),
    CHRISTMAS2017_NOT_MY_MOM(AchievementGameType.CHRISTMAS2017, 5, "You're not my mom", "When tasked to stand still in Santa Says, sneak");
    
    //</editor-fold>

    private AchievementGameType gameType;
    private String name;
    private String description;
    private int points;

    SingleAchievement(AchievementGameType gameType, int points, String name, String description){
        this.gameType = gameType;
        this.points = points;
        this.name = name;
        this.description = description;
    }

    /**
     *
     * @return GameType of the achievement.
     */
    public AchievementGameType getGameType(){
        return gameType;
    }

    /**
     *
     * @return display name of the achievement
     */
    public String getName(){
        return name;
    }

    /**
     *
     * @return description of the achievement
     */
    public String getDescription(){
        return description;
    }

    /**
     *
     * @return points of the achievment (int)
     */
    public int getAchievementPoints(){
        return points;
    }

    /**
     *
     * @param name Name of the achievement
     * @return the achievement with that displayname. Null if not found.
     */
    public static SingleAchievement getAchievementByName(String name){
        for(SingleAchievement ach: SingleAchievement.values()){
            if(ach.getName().equalsIgnoreCase(name)){
                return ach;
            }
        }
        return null;
    }


    /**
     *
     * @param name Name of the achievement
     * @param gameType AchievementGameType of the to get achievement.
     * @return the achievement with that displayname and gametype. Null if not found.
     */
    public static SingleAchievement getAchievementByName(String name, AchievementGameType gameType){
        for(SingleAchievement ach: SingleAchievement.values()){
            if(ach.getName().equalsIgnoreCase(name) && ach.getGameType() == gameType){
                return ach;
            }
        }
        return null;
    }
}


